apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./longhorn
  - ./victoria-metrics
  - ./cloudnative-pg
  - ./garage
  - ./ingress
  - ./keda
  - ./kured
  - sops-age-key.yaml
