apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret-key
    namespace: authentik
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:dRU1xJxbgqAaf4+sBrUBXqhxKa8gzymn/uOwGdptrCjlwfVyqRvsle0LVILSMynQfPC1xk5/tZuJEZEjou8Lb60mX+L/G2k3ZnnW/QvtmhjgJE3LzGH2gny7HtV1EsRw4+33HdvBwJZx82Ba,iv:5v9ZvRnvzOw4h8cBzJ2RmcL0/2P8xv9NyvQzWWbXyy8=,tag:tWhh5uPbcpg5t3V/iJIzUA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHEyMURhQSBWL3lK
            STlHd0lHbVVHa0thZVpHbkNDZDU0b09OZTlDTHFSaHdRY2cyWEZjClJoNUJWVk53
            cmRwaklheHJuWXEwMlYwSGtwelkxVUkrUGJkQmJRMDhkR0EKLS0tIE9BVEFodzRC
            ZHNCVUFKWi8yR3RnY3F0NVJUczBFMllYRDMxamFxcHBTR2cKcbTBKwNzc7le6bCw
            fDq3Vu8/mccx5gfOYo5R6gHkY3O3jEkeYUDgEGrTBjc995+lhfT9SRop6oBS9onW
            6huYIA==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICBbJZYAoaiso9r80YdbBkqFZ1bggET4EEkzZ9ckBbGW
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHFodDFMQSBMbVlK
            V2g4WEw5T1ViUEVVOW5WNXQ3WlVWdWJqRTRQR3oxOTlDTE9lbW5jClZMdm1kYklM
            MWo5TGU5VEhPZ2xHYW1MVW12MThEN3UxSnBwdzd6WWVhRzQKLS0tIFNnWTc2cFhJ
            bk9qZzhROVFYd0NtdldBdUdjVzhaK3Rick92THpOUUx3eFUKyQ6bxfEVHLyVpfFQ
            Z/z5N/ynps1PnW3OjJyMJr4wFnvPPzKA3EsnsIoZmVsT92f/DaXX+jnunLKKVEc5
            XMQfCQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICvbJQ3KnO165S9pyfQ5qHXFv51cw3LmsvUn6Xo2Bbr7
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaTi9obXJNakkyYkVGdWxZ
            R1QxN2lpakRyWFI4UkY3VnB4RXQyN3hRdTJnCkRhL2loNkpnR2dmUG94NCs2SFpD
            ZzBIMVB5R2NSamxGSEhTbEE0M3FyanMKLS0tIGVJUm5NZzV2OUpSR1QwZGVUaEgz
            MWhIQmVRSzFmUGtDRHBSMEdUcnd3MFUKUox3eOgmz9fc1vRBDvNhaHmJ13RBBfqu
            1OAEIHnUgYiyJJ4WJ7lZqnE49IAn5Oof/6lh0hcDbshKEzpZw5l9Cg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mnacljduxclddus4xa83h079w0yqz94h22kxwxjqj26vu6fg2ckqc3gymn
    encrypted_regex: ^(data|stringData|password|token|secret)$
    lastmodified: "2026-05-19T02:51:37Z"
    mac: ENC[AES256_GCM,data:oFmR0cuLGnBIiWvyo32NPSF7B2x/+qFnGPVgsKcd2AYyurSgrSheJhCtK+RDavDp1P/hJtH/RfSfz93etQDStYJOvbhXIuYQScL3qYUXnPutfVURoGpSNrtB98yExUvzs3ucgGal/HBTPmwnlm2gmO62SYpQCH66h/5v8NgRu6I=,iv:Drs1j55JD6PmigU3Lhk5WZnjKB/M+yf+tKhE1+6yHWY=,tag:IoocqaIohtqn6JrynWQaLg==,type:str]
    version: 3.13.0
