apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-role
    namespace: postgres
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:DMW5N651qA8g,iv:nNvoqF939wtPU376l9hsMQHJ9N/fdJ4DoqKEISOxaKQ=,tag:LFIWmV6WuOHeSJE52Ntacw==,type:str]
    password: ENC[AES256_GCM,data:Od9Uaz0hyafqA3bqUpV5vSUvgPvUmmDklk4oXtpZSOpOtAySJbjVfmdTvbJ4nglGcP0YuOlEtJhJ0ysLav55ig==,iv:1yR2YxYAAOopGSH+A+QLoOK5EZe2OQ1zJHZEd+VJKlg=,tag:v55MawSmrTeUCD7kTqmsYw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHEyMURhQSB3b0Vq
            SHArREVOMkZoSjRsVGFWWWZkOWlQaHM2MFkzVG8vQjdXVUNvU1hNClB1RytOME43
            QUxNd0tjb01FTU1xejdPazhTQjVuckxlbkNBOTRTZkFXWWMKLS0tIFVTSVBOM2xY
            cVNYUm1RSVZpaTA0RnZob0NTUTlINmYvSkY5ZmQxcFczZVEKkaQdb0h6sXMFbbha
            3PxPFHVlAD0PIRkzZYchNBr6fXiyfBrRqgjOZLaYLLQxZkbDNPPXg7Sl/+IRBkUB
            ijEYWA==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICBbJZYAoaiso9r80YdbBkqFZ1bggET4EEkzZ9ckBbGW
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHFodDFMQSB3dVQ0
            YjlrTER4OUljOGN4Q0Eybmd6bThZdE9IUVRudkQ2ei80WEZJOUNZClJzSzNhRXVU
            cVQvVjc5RDRPc0s1bzhaT24xUEFCZlF3aDhQZ2w5NGtGOE0KLS0tIDEyZGsza1Qx
            eUYyYlBrYmdjZWRWcWtRaFY2V0RWcmx3bTBXeU1oRjJUV3cKWIoFaj0jBlxnBatU
            0uvHM4BrkRjKejM7W52l45jB/pW8JSuG74KPCX2gCWoWNK0HgfKJhRK4I8wrvtLx
            RRRu3w==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICvbJQ3KnO165S9pyfQ5qHXFv51cw3LmsvUn6Xo2Bbr7
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGRFd5MTE2TW80R09hN091
            ZENhMkQvSGdoN0VPSzFEMTlMUkFIOWNNTDNzCmVGeG5hQ3NFZG91T0ZyYlVRRjJU
            RlAyK3BaNXdqQnhhTmRqU1hIM29GaGsKLS0tIE9aNk5hbWlWa0Q1bmtvUWZPS0Zh
            VStLOUJFZEl1NjZEU0xFSEZjZ1kzTkkKfwIcdCkSHU7uAFiX7ysBY4yIxwg+UG1v
            7z4493yTc9Sv9eKIHZCrtL4jQRDtdwQ6xSLdW46/NythueC0h8XUjA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mnacljduxclddus4xa83h079w0yqz94h22kxwxjqj26vu6fg2ckqc3gymn
    encrypted_regex: ^(data|stringData|password|token|secret)$
    lastmodified: "2026-07-28T01:21:15Z"
    mac: ENC[AES256_GCM,data:8GZdrBmApZXIKemnHgo7Nv9hXoHIUKHhyhzD9UDj1Ufm/pUgQOX5lPAGissCtrMzYXsKFOzG21i/0TGcSgWH7ZFxcm8aGkOo5tnuLE0tkKAwguSlkRA8vrysh7JG3NUbdXhBPZypuao/dyiNHXs747zcUPglY3D8wurlq0W15kk=,iv:b0iM33o0RzZrgpS0J1sahwNxdMXStjB0xgxxEK5mALQ=,tag:g7kOsuw7zU9oeixWNqTUPg==,type:str]
    version: 3.13.1
