apiVersion: v1
kind: Secret
metadata:
    name: db-creds
    namespace: authentik
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:RSBORKJ/XHz6oz+bUjonfsYWT4PYRlgug/aXXB4Kl/gC/ONA9HcvPwiHvFbuRqm3xjBC0jCfUW3pQnaC7Jg//JVrOKC5gW9DMwsmtr4RyVLQAfvg9m0QSxq4rzAgmrfbz/gXtcMFV+3aGY9aGQd8xIKjhrrGbvdwyCGV0ugYb2TY1lEdE23smcaqOeGjohTOj5Epr2miiSo4S8kxIJiKMGm8gcr2cX64MTaAxvTA8uwQnB4CCOeYfBt3cPcax1RZqIrLrx6iBFgbFIhxng==,iv:lTvq/abygyI9MxIXzLEUNdH8aS/XbsR4oTm3epLT11M=,tag:cFwjf/OiJd7hTXGuhFxakQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHEyMURhQSBrYzZQ
            aHRKNnZOS2ozK0hhejgvdVdwT1UzcmYrSUErWGdPRHVzdlZuQWtBCkhlNllIRExa
            dzc0RXczM0NDcHJWc2xxUkczWm1KemRScXA1Qi9TR05LVlkKLS0tIGFFUlI5SzdP
            ZC9vSmYzRlJ4d283alVtQ3NKR0xRNDBMYnNkS25HQ05EeE0Kd3gPYlMIQ8ZLG3RZ
            Q0ZIWJq8X9gYv0joPvKVVpX02JKgmXPQD9VavKmzV1dLEnOobG8OHTN3kSPBOxHP
            7poyIQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICBbJZYAoaiso9r80YdbBkqFZ1bggET4EEkzZ9ckBbGW
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHFodDFMQSA4ZkV1
            MERKNDBoTXpOOVJpTnZrc3RNZ0tFZGRyWGpGNXZRdWY4RzZndFd3CnNVdVhWWWd1
            T05CajZPUVlTQU5QMmc5RTB5M1NLU0VOZnVuRWE3L3FuUXcKLS0tIFBJTFpFNjdI
            NmlLTFZQa1QxSXh1MkRTMjlUYmNpNUxtbXpwa3ZqSE9yczgKTPD8FnaVkM8Py1yE
            IKOVWIKDUbkWLra6sqIeyQ3FBKc4+xqaPdAbgdtvQXQX3qqPVxrt7LCX4ZLXI8yG
            GXXFYA==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICvbJQ3KnO165S9pyfQ5qHXFv51cw3LmsvUn6Xo2Bbr7
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsMzVKdFdXVmh4SlF4SExK
            U24xek1nMjRFK1dGdUFRYUNNbktNVVVKd25RCk44WmxpRXJJK2JTZFM5cVZCNTYw
            UFVKNS9HTlhTMHd6VzNNbWk5NlRFc1kKLS0tIDJkbVhaVmZVT21UM0R2NW5wU2I3
            M1d5RGZqTTBrV3N4am9tYS84SWtXVEEK+K4e5s/MyAfa0AiLPoltFFaZtV6s41/8
            nfPyuCMSYnaj2wh1H2zqnG7GKO4moWh6poTh4B4vZ4yh0fDc+o2ujQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mnacljduxclddus4xa83h079w0yqz94h22kxwxjqj26vu6fg2ckqc3gymn
    encrypted_regex: ^(data|stringData|password|token|secret)$
    lastmodified: "2026-07-28T01:21:16Z"
    mac: ENC[AES256_GCM,data:bqKtxw5t5V7Q+6heAlS7DsLwX32z/0DJb9dW6Nl0OvjqgZd/REdlEZbOvM9YGzRzVSzBPyBmksfGRTBiHzm47QBmuqd1HWbIYhvHk+9xyUbElBaDvDDHSMndthVEHR4Or6GwOxdDSwHRgLKrPFZ0ReNcokHn+/Sa3dzp58NCpKc=,iv:1vx9e+ki3XOXxXiWrkFQ3ChQvebQj/VZSVTHf4BK1IQ=,tag:XyXEFzII5bnvlIxm46D5bQ==,type:str]
    version: 3.13.0
