apiVersion: v1
kind: ConfigMap
metadata:
  name: attic-config
  namespace: atticd
data:
  config.toml: |-
    listen = "[::]:8080"
    api-endpoint = "https://attic.maio-tech.com/"

    [database]
    # If you see this. This is a temporary solution until proper database roles are added in one of the next releases of cloudnative-pg. Please disregarard.
    url = "postgresql://ephemeral:CHANGE_ME_EPHEMERAL@main-rw-postgres-pooler.postgres.svc.cluster.local/attic"

    [storage]
    type = "s3"
    region = "garage"
    bucket = "attic-bucket"
    endpoint = "https://s3.svc.maio-tech.com/"


    [chunking]
    nar-size-threshold = 65536 # chunk files that are 64 KiB or larger
    min-size = 16384            # 16 KiB
    avg-size = 65536            # 64 KiB
    max-size = 262144           # 256 KiB

    [compression]
    # Can be "none", "brotli", "zstd", or "xz"
    type = "zstd"
    level = 8

    [garbage-collection]

    #interval = "0"
    default-retention-period = "14 days"
