apiVersion: v1
kind: Secret
metadata:
    name: attic-config
    namespace: atticd
type: Opaque
stringData:
    config.toml: ENC[AES256_GCM,data:WpSudi2KbQu4GFAGqEnHLTxAr/C1jAEvAGLc2jPh2rBINZGR9D82BUxWXzA724div49inKD7CXI/ze/sMelXfXqy3G+SeIn1w7skns0Mg3MbfqbOLQdFIXSVBGKOwesrYJGz2Mc7LrXA/ZhHp5ikep+hVHtIKTlqV3yqroet0gIUyF5RzKvVpX8If9V3shZEf0o2U3Fj/GXX1OxpPmA4typ4UUBYIz3Y8I5hTcWXLV4PpdOPaC7A1whmSYPm+rumjvlTmiyR+8pI10/7rg8vrv8C3PrAmQuXQda/xGRVy0wp9t7xMvbQ2bwlqzDiAHW+MO5sFPUidG0g8+KxWCSAAmOM1s5rG6/RQ/n4QYvDbQ+obtRu71pBbPqa8WAjS1atu8/7jDafBql6dPEqD4Q4xL1TMZt68C8sc5ht2Z45bqcaiU0GHe7BKH81Q/rMYAQ8cdxj65zI4GcRHcuZP2t1O4TbM+/Az4vadbYt+m7h4n2J7gvCdx+f2mDQNCSKqqPVhxuev0KrkKJuuNkpwPoFVfr6AK4FgWw/j5kmjYzgmrQLNKkgv70vN4Q1zdWNJROZNKsBs4VF1pCHx0K5EEhztFMjgeEGzfBbPruPOhD7bV+Qpa0Q0Pe5GyOSwBdATqozU56VUatKmzJUmJARYaJwWfH9CcK8FEyxQfy+aE9BUlQzSpq7hglIwUDkVlSL1CKsV4KPXcr1aLTCIUi5/NQNzuogznmb8Wb7WchkkBPTFky+n67kFLTJ5+T0EEW93qX8coeYXWL8xojN/5AFVM4B0SKAYiofetj3m8oFe/P/P2e28g180l6ljUWXyE2Mtvsvugz5fZrRwkp1xazu2BPsXiY/p8K3vKgmJa7wT2v++k4ojQD+n3s=,iv:OxXy7RjvEmd55lGxhTMvDW0TD8O0MDRT2Jv1GvKA56w=,tag:+nUslRNiMDjqhsFyMKJwpg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHEyMURhQSB4L0V4
            S0x1b0MwY2VBdk5jRGxleVpsVU1BeEF2VmRPMi9yWlYvQ2NHRFdjClN2U3ZZTitV
            NkZSSUNTU2w3L0o2bmc4WGx5U1lGZkNXYVlFTkVVNElFUmMKLS0tIG5WVzl5WkdQ
            cE1XdzFCbE0vMllDUGc2UU9KV2JLNnNQTWNsR0F2dnJpRG8K/2M1K19hA6N/i7vR
            sD9sW0zRlSRLVVMX7CZcoAXyNx1EAH/LU0+dKh9DbRXZ/OFJ9fimNh7tJqtAGib4
            plncTQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICBbJZYAoaiso9r80YdbBkqFZ1bggET4EEkzZ9ckBbGW
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHFodDFMQSBMejNR
            NlJaYmFOeGlDeFdhbnM0VnB0NGEyZ0VqZGV4WlM4VlY4RGJkRkJjCjNsT0lneExP
            THZGQ3NwTnpkbktpU3lvaUw5Vmxjcys1bDRmS2FOZEpVQ2cKLS0tIGVpU0wrOWg3
            ZnR0TlM0QWJSem1DakgzNUwxMjFVMFJqZFNXZEQ1cGVCQTAKtthW21E1nOuduz1y
            ps+rnxo93pIuulniGj7UeTUZ6rRa+xhLc/TF7S/kFKwCbyAZLaOEW3q+old/mtou
            pd3SHQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICvbJQ3KnO165S9pyfQ5qHXFv51cw3LmsvUn6Xo2Bbr7
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtbTE1MDJqZk1sQVJQdWgw
            K1dKOCtGb1FRYzdZV1VYZlFKRVVONXZHTUZVCmZ0eUlQODNwSjI5Zm0rdmdJUTd3
            NGNNVFdFay9NRWpDenUvbnppNE1wclEKLS0tIHVsRjE1d0IwdEFjUkhZZWcwRFM4
            eDVZTUpJemZLdDJmckp2RDFMWTFWQTQK3Z0LWB0T/kJPlDs76SqHRzPQ3Cq+icCY
            GFIcJds6G9yHycylyYHROVX9oAzg22UkAaZn1g5FStOjEs+ioiptGw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mnacljduxclddus4xa83h079w0yqz94h22kxwxjqj26vu6fg2ckqc3gymn
    encrypted_regex: ^(data|stringData|password|token|secret)$
    lastmodified: "2026-09-02T04:25:36Z"
    mac: ENC[AES256_GCM,data:+D2t7My84+mbNs+NA4bMxYIFB05OtfVjWNVO1S67PFAilSLmSLBVSmjejyW/lLuvSXYegRR72n9m8mW8RQSFvnKNTydhK5x5rbQLyodnp5pFp1RGv0B2mgNF0yU0mpbdeg5x1dZcVFHxJ9TF8oVqCPik6idAzvYDyVgJqShrkR4=,iv:yfkywbBGkG2Tu2ds+9mYCDy3HBCGnfy9g+5au9AWv5U=,tag:mHB8yt/PrtTvukwnz+G44w==,type:str]
    version: 3.13.1
