apiVersion: v1
kind: Secret
metadata:
    name: attic-db-role
    namespace: postgres
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:ZYxWhfU=,iv:kaSLAP8BP3M+7ZUhmn80534JQWAXxiADXefIoSpHfaM=,tag:ukAg3p92wuJlJ7In4D+zGg==,type:str]
    password: ENC[AES256_GCM,data:CGRzUkRXRvDJ2bKrxzLa0S+pdqj1gsTwKJ0Vfepu1zvAA1CZItN828E4UzRETy7ZVkBCgy6hZDg1vexMCdjJTA==,iv:DwbfgL3Np2QFf/ESJw0pmbWn5c3uxXj8zkeWsTHJyhQ=,tag:7E49i2xKcIVDXwsaQGJj/w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHEyMURhQSBtWWl5
            V0dwbXh0WDJCZC9yRkhTeXRZUmtlSDFSeTRMR3NPNkQvT0d2YVFVCm5xTzVQUnFY
            N3pMdUdUZE8ra3BFR09lVm8wWS9NZlFpUmI1QXg2QnZ0Q1kKLS0tIG1kRm0xY0Ux
            T0VHWVNvUlZ2djVaLzlnQ2dhbW4zYTBHUGtuSmVlRUI2Rk0KRpeAFYT3VNT8V7Sy
            IrH5M7PoKg8VAZJFDeeY/U8T22TQrwPaiB/TVgFFW0k/4N9aaa9nw9yfc+ElUF/7
            OMHCXg==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICBbJZYAoaiso9r80YdbBkqFZ1bggET4EEkzZ9ckBbGW
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHFodDFMQSBoRE8w
            UHVjQzRYdWNvbjVGSEhnYWR1ZDdIMmF6cVB4amVycUlONUNkY0hVCitleHk0QXhB
            Ny91aG5YWGtLUWY0MjNWSERwWm9jY1lEOE5XQ0NDSDZzbGsKLS0tIDd4UFZ3VnhU
            ampzaGlaM0RLYktNT1RsbWhJdU4wSEFKSUR3dmpCY0RtN0EK9qjzrPVMOdu8dGQE
            RI0MEGUAaj4hQQc/bptvdYwP6hD0XvYnpJtvop5hZK+QZGPAYJqUGfMbObLnzH+l
            ITKKUw==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICvbJQ3KnO165S9pyfQ5qHXFv51cw3LmsvUn6Xo2Bbr7
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZmtENG5lSitqajNnb0xu
            clNqTDd0TDcxcDFyc1Q0RFljekk1dkVLMkV3ClU2ZDM1VTNxSWZiUTFPTGtBc0xE
            SmlGandoRk1WUngrSHBOZUs3TEU0OGcKLS0tIEZqdXlUckVNUGhBOFJMMDlsbUNJ
            ekRPbzlic3VOTGkwZnh5Qm52Qk9MeW8KgZSRuZfdf0NM47G4IphmkkN0HR0LGQD8
            TPFyKe7e7sBKpkhyuEqdIvdenoKaEGZgcJoGf5li8++zfI7jWz59fQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mnacljduxclddus4xa83h079w0yqz94h22kxwxjqj26vu6fg2ckqc3gymn
    encrypted_regex: ^(data|stringData|password|token|secret)$
    lastmodified: "2026-07-28T01:21:15Z"
    mac: ENC[AES256_GCM,data:4q8qLQ7tVshaR8ioS3vMxi8HwJX1LlvjPwOdnqZVd7yvNlzO+D4tMmnghDoi1WTsrfBmGkpGbv5tb0Z0x9szJpzhHTmsFhderlNwHre6J3KTL+a1yQzNC9B6QpNHCWoA1bhaAjTC0Ivd+Ip2+lsl376uQ3FiuVhqyefaly9FoY4=,iv:To4cHmyWji5mHTApFcx8oOVbEiVHspA8uB7OlwR168Y=,tag:TdMvimomNhnuSnu//t2JxA==,type:str]
    version: 3.13.1
