apiVersion: apps/v1
kind: Deployment
metadata:
  name: attic
  namespace: atticd
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: attic
  template:
    metadata:
      labels:
        app: attic
    spec:
      terminationGracePeriodSeconds: 900
      initContainers:
        - name: attic-migrations
          image: ghcr.io/zhaofengli/attic:latest
          args:
            - "--mode"
            - "db-migrations"
            - "-f"
            - "/etc/attic/config.toml"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
          volumeMounts:
            - name: secret-config-volume
              mountPath: /etc/attic
          envFrom:
            - secretRef:
                name: attic-s3
            - secretRef:
                name: attic-jwt-secret
      containers:
        - name: attic
          image: ghcr.io/zhaofengli/attic:latest
          args:
            - "--mode"
            - "api-server"
            - "-f"
            - "/etc/attic/config.toml"
          startupProbe:
            httpGet:
              path: /
              port: 8080
            failureThreshold: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          ports:
            - containerPort: 8080
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - sleep 10
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              memory: 1Gi
          volumeMounts:
            - name: secret-config-volume
              mountPath: /etc/attic
          env:
            - name: MALLOC_ARENA_MAX
              value: "2"
            - name: MALLOC_TRIM_THRESHOLD_
              value: "131072"
          envFrom:
            - secretRef:
                name: attic-s3
            - secretRef:
                name: attic-jwt-secret
      volumes:
        - name: secret-config-volume
          secret:
            secretName: attic-config
