apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: attic
  namespace: atticd
spec:
  parentRefs:
    - name: gateway
      namespace: ingress
  hostnames:
    - "attic.maio-tech.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      timeouts:
        request: 0s
        backendRequest: 300s
      backendRefs:
        - name: atticd-http
          port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: atticd-http
  namespace: atticd
spec:
  clusterIP: None
  selector:
    app: attic
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: attic-traffic-policy
  namespace: atticd
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: attic
  loadBalancer:
    type: LeastRequest
