apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - db-role-secret.enc.yaml
  - database.yaml
  - bucket.yaml
  - garage-key.yaml
  - key-gen.yaml
  - config.enc.yaml
  - deployment.yaml
  - gc-job.yaml
  - ingress.yaml
