apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - database.yaml
  - bucket.yaml
  - garage-key.yaml
  - key-gen.yaml
  - config.yaml
  - deployment.yaml
  - hpa.yaml
  - gc-job.yaml
