apiVersion: v1
kind: Secret
metadata:
    name: renovate-env
    namespace: forgejo
type: Opaque
stringData:
    RENOVATE_GITHUB_COM_TOKEN: ENC[AES256_GCM,data:XG3Z3P9tbJQJD0oHS3si1RPU0T0oDgWEIB4IJ2RD51KlPcn36xRyvBpsuitsvpOaalK9t/S/odMTF0AmA0D+mDgKgmFAhWMmx8//1uYumJiVTzRWcdgR2956fOQa,iv:loM/jT/4bOLIFrUxnbOz4JPwn1I+J2R0/KoDWVlPIAk=,tag:7RJXo9oDK6rZSxd+9PkwSg==,type:str]
    RENOVATE_TOKEN: ENC[AES256_GCM,data:rZyU8tj3DOzYFVjY47cUMZsnYedoWRPhgkQQiVt3DpldNLhIclUzhg==,iv:h2/amMdLjTrf8tYAAbuI69OPsxTxifYkEq+1SvqrQ7s=,tag:qhOdecYKw4n+WzrCPYnXQA==,type:str]
    RENOVATE_AUTODISCOVER: ENC[AES256_GCM,data:HQJfyA==,iv:RkHt1sX+o5qDZ0dQTKU3XULFZn6UtP72rDi//eLfodc=,tag:i3DjqscrzaLkOQ6HvsgP7g==,type:str]
    RENOVATE_ENDPOINT: ENC[AES256_GCM,data:MdP9y+xZLoRjvkq18fJDVZsJJg/8hZY5bAmk+FDzHA==,iv:NDM2DSUt5NNqWpLA+R1S9zSliXcA6yR0FJqk8VAbSyQ=,tag:5cjRyejFbHPW0R3DHHYb5g==,type:str]
    RENOVATE_GIT_AUTHOR: ENC[AES256_GCM,data:rK151AI8CszPE+MlxYoIWiFR+iNOaA7piy30f4dgjOPOXXM0,iv:Tacywf4U239JjmVO6i+HTgOhcYwnl0DKOyN52BQgHfY=,tag:DhgLvSdcr+bXiDfLTpdO6g==,type:str]
    RENOVATE_PLATFORM: ENC[AES256_GCM,data:JzUEBwr8dw==,iv:efsaDmQ+Ex7e+U9WajpEjvx6vydgtCjOELV1XAFsMng=,tag:oChQnli86BO3/yjG6unf0w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHEyMURhQSBQZlpa
            S281dFlOamNLb1hubm93YWtDQjc4YUpWeW1zclpwVjh0Qmh1Nm1BClI0V0Q2R3ow
            djN3OXVnMjRhVnBjZ2poVHorZ0t5anRxQkNwZmJDN0duazAKLS0tIEgwdWorbE16
            VkVNME1wVmU0UXFSMmJvdk5CSzFIb3EyWXo4NTkzNzJvWU0KWIFujoYWuPgCURXW
            sV5+yqQqNoc2DCVJrRuky0Wfi4Rx6KESc5IprQLWiIh1T2lg2hbPDU2IlvA7ryCA
            3OnYUQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICBbJZYAoaiso9r80YdbBkqFZ1bggET4EEkzZ9ckBbGW
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHFodDFMQSBGOGhp
            RWJzeUZqdUlNSDRTYVRTTGdvdGF4L01hQ0Q4djAzNTd1NnVlRlg0CkpWdS9mRFcx
            d29kS1N1M1VkL0lMT0RYTDA3RWxGMGZxWjc4a010UU1mSzAKLS0tIGNPeVVBUHV4
            Y2FsV25Qemt4U1RUQXI1L1VYRVZpNi8xY2FwT3ZoUGVDVFEKVOBIBtsdCNRK0znU
            7Jm9B573S2qTLSEdEaywooi3O7K1VysR93xsCAUyKSiMzLmeE3eatZiSlUs3/Z4Q
            kHJ9nw==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICvbJQ3KnO165S9pyfQ5qHXFv51cw3LmsvUn6Xo2Bbr7
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFNlU2NnF2VllWVE94RTZR
            eXRPZHc4ZXV2ZUcreUNVL3dYUG5VRjNGSUJ3CndhSnRmWDU1OXlzSmtnT3loV0Ns
            aXZyYm5Nc2ZXMjJaUGltRlFKVnRjL00KLS0tIGlWamV3S3RLeTYxejFHSjJCdjFZ
            N3dWNUJTbk9SQnJYTXk4SVBUek5lSlUKakxfdRBazlP6uSjxDTAftFJEPPsFi/Le
            pOdiXLbtjxfpxGaQH0Oqv4FA/5Us5bhS9RZFm2oBf7SiKcg3pgTDkQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mnacljduxclddus4xa83h079w0yqz94h22kxwxjqj26vu6fg2ckqc3gymn
    encrypted_regex: ^(data|stringData|password|token|secret)$
    lastmodified: "2026-06-03T04:29:26Z"
    mac: ENC[AES256_GCM,data:z0Mh8BueHlanl5VxpObzhnFHtMv5gGj+aIaoEYOYVVzk4Ncpe4vcFHIireIrvi+DAWZStUDXgmE3xCRLNRMZyv/1xdbtaHHU+hFYhmPSp/j7u/nBEiY17dGbk2SXOg0yYociALiHBtKWXKQeD3L6xk6pIpcOvsKcp7nOCzPCSrE=,iv:/PjhnHDKvg7sHeJLjcNwLt+Ysnt22Ort4N23PsGBr40=,tag:N3h8WQXI0BaffhQbFtRjvQ==,type:str]
    version: 3.13.1
