apiVersion: garage.rajsingh.info/v1alpha1
kind: GarageCluster
metadata:
  name: garage
  namespace: default
spec:
  replicas: 3
  zone: awawa
  replication:
    factor: 3
  storage:
    data:
      size: 10Gi
  network:
    rpcSecretRef:
      name: garage-rpc-secret
      key: rpc-secret
  admin:
    enabled: true
    adminTokenSecretRef:
      name: garage-admin-token
      key: admin-token
  monitoring:
    enabled: true
