apiVersion: garage.rajsingh.info/v1alpha1
kind: GarageCluster
metadata:
  name: garage-main-cluster
  namespace: garage-cluster
spec:
  replicas: 3
  replication:
    factor: 2
  layoutPolicy: Auto
  storage:
    metadata:
      size: 1Gi
      storageClassName: local-path
    data:
      size: 10Gi
      storageClassName: local-path
