apiVersion: v1
kind: Secret
metadata:
    name: sammy-discord
    namespace: openclaw
type: Opaque
stringData:
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:TNjFqinFqbCgTJCkuc26MvMSMyzqrr27OVKHL2wMQ/LBl1z9PfOjCxz4lHPZSw67z8WZJ/EYOaUIyCJ1G7f5J/tU0yMa4qDB,iv:fDaa1Zq62B7h4OJH4JGuWt/V9R1n8EmImc9UNb10t6M=,tag:wJHy+jC0V1i7lEKZ72Z3dQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHEyMURhQSAyRTFV
            RFZRWkZwbnVPTlpFdzF2SHoxWnlwTVdValFRUHJCTnFZN1ptT3dZCnNlV2VYOWcy
            SmZHZDJFQlFKc2VWV0F5NWJnUGtiOEZIWUI5aUxTZlFjd00KLS0tIENEWnY5MzNW
            cHpZQzZTWG1PYU1uK1ZtYjdCZVZEUGU0M3M5OUJ0MU9pWncKFz7mPnAXa5XbT3kT
            e0eqv4Pd8qCtir5pE5JMhEAImmYj3nacq/olr+JsSYWiP8vGC7EERYB8rFT8DBtY
            eZ134w==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICBbJZYAoaiso9r80YdbBkqFZ1bggET4EEkzZ9ckBbGW
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHFodDFMQSBybDZn
            M3IrTkVMcWNRdUlEbXJzTVZ0NDg0emNUTlU4aEN6Y0lsaUYrM0VVCk1rNGtDTVBX
            UGk4dXk3bURmMEltcTdBR0ViOXBocUJsZ21qdmJJcXcyLzAKLS0tIHNzLzNpVTNl
            SmppbUhZY3AzZ2hkcmNBSExUWm1teUNLRkErR3JRenA3dE0K8Fz2PxdNdezVuQs1
            pBFSaR3D+5OdiDEljJsrMrSrd+mmnUFXIELfcZbYYp8N1k0COYlSFX5N0cepyO++
            kUV/WA==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICvbJQ3KnO165S9pyfQ5qHXFv51cw3LmsvUn6Xo2Bbr7
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUMDQvOWlVai9hWDk5Q21R
            UjVIQWE4dVZ2YWRTVnBLTExiL1ZlaytaYkdZCjVkZW8yMXFuSVk5MGFTeVFzTFQ4
            bEhVODBpTDVFM0xKUVprTkluSjI2eGsKLS0tIHM2cnlMenBmRUxjMitwalhsdnpo
            RzJSaXdxd2pNNXFONW1VTCtkdGt6MmcKA/oWiPcYKB87qdHgmwg/hf7J/L1FLxX1
            gLGT97Svn6JieGV0MiRwJlUe0Y1U8T/3Odbj11mXyxzjMP+zu87XPw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mnacljduxclddus4xa83h079w0yqz94h22kxwxjqj26vu6fg2ckqc3gymn
    encrypted_regex: ^(data|stringData|password|token|secret)$
    lastmodified: "2026-07-21T22:27:50Z"
    mac: ENC[AES256_GCM,data:vwdTh6c9An/0kMu32CIwQ0aVB6FQTNG/dbcx7o/OnuasUJR1EAg/re2fSVoE7Oz0j5Xa4nufzGRRyfO4ytfNw8ZcdL6x47jMN/oVyDVy5nZzVehaMJrt7t75MO2QA5fQlXsdxf4gbwdDiGRbASeuz8ib1c50h1owjbDO3squVpQ=,iv:vXW8Cfl1rB1A6jpL2uOsU5M3lfsv9TOjrs5KAfNt8J8=,tag:uJDn+cjdkJNd2T5tJVQRkQ==,type:str]
    version: 3.13.1
