apiVersion: v1
kind: Secret
metadata:
    name: georgie-env
    namespace: openclaw
type: Opaque
stringData: {}
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHEyMURhQSBsVzRh
            YTkvbGdiZ3M0Tm1xZkdwL0tHSTNqVStsSWtaWGtwcCtwYlBuS2s4CjhJWm10YkpU
            K2FxMEk4SjcwdHZMVmVSZ1k1aE1CWk0wOXd5M3dzelBndHcKLS0tIGNUdHhDRFZv
            OXJPRGlJSTRtcXRiZ2p3T01kVFZKSlUrcnRRSXNiU3V0SmsKiQe1DO6sewVGM3pe
            mUe75oxQyadOSGYihfkVLqzy6V6l9D1KNswGvUmHqM7elu9HeSVsrzWI/YbODeMR
            yzw4Sw==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICBbJZYAoaiso9r80YdbBkqFZ1bggET4EEkzZ9ckBbGW
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHFodDFMQSBDcHlR
            ck9SSXNnam8zMGhYWUNSZDYzdk9LWUk2Y3ZWQWRGNDZYMnVibVY0CjhNSFhNdTgw
            OWw5NHkvTjNJVWtROWRFejlCblc3RnVNNlRuaVBiYnRXRkkKLS0tIGMyUHVxUTNy
            YWlaQW9hSGlIeGs3dkIyem9od0RnR05LMGp1ZUlpY01YUEkK88jJXafGUFISI24n
            d6gI0kEZI297gTcINlgg5qQvx3H3AWEh8vhgWN/bqxC+ORTuqRAJBJJUnwrrP0Gr
            5IysJw==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICvbJQ3KnO165S9pyfQ5qHXFv51cw3LmsvUn6Xo2Bbr7
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZ05LVU5zYVdhTURNZDB0
            Q0t1UGw0RThJVHRvT0htWEZMWFJQRXBtcDNFCkZwdTZqc2o4WURnLy91QjJQd0kv
            blJsT096WjhRaStsMEFiWStpZ2lxYU0KLS0tIEFLZ3ozY2NNVkUrUFJmK1c1UUsx
            bytESkFmdDZ3L0dPM2FFN2sxUUY3NTAK0zMN2BrjPi6cpYEMNR3UJrU08yFFftZY
            oD/ix6uGQ+RLrODWeUdKSn77GYozPYW5YP3KXf2P8jFUCV7RwKxvGQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mnacljduxclddus4xa83h079w0yqz94h22kxwxjqj26vu6fg2ckqc3gymn
    encrypted_regex: ^(data|stringData|password|token|secret)$
    lastmodified: "2026-07-25T07:59:46Z"
    mac: ENC[AES256_GCM,data:bCpKmU9toeZIpwuwoYjPlhcD2VqiOEMTuEn9WBatuzO41pzDa/zpPJHSS8V+JpuvZo7G2rbiS62wGY2XOthQFTNcXHl6dkVNT/iv8iZ6dP46wyzuOrObOwb39sBy9x173zSZxkK7BzrP2RDEta+DL40P8BH0KZIkg5athBZXAME=,iv:Du/bzPfIfnGhgiyZP6DYy6TybyXQOI2sq4dH3D14TEQ=,tag:gBmOlIu2zGUJp2P7uzORnw==,type:str]
    version: 3.13.1
