apiVersion: v1
kind: Secret
metadata:
    name: kevin-env
    namespace: openclaw
type: Opaque
stringData:
    GOG_KEYRING_PASSWORD: ENC[AES256_GCM,data:pATDcZripRwI+vdJsvvkPWqkG4VsBdDms1PSZWlBtVDgHWC2VpQ6N1kRgr9iAYUIiBIJ/IXhFXlWLnKMj8I1PA==,iv:YtjdmpkkyE3JuCT+lpheb2znPYmOokoZjk9cjVDFsXQ=,tag:G/SpbCgz8ApO/PSsdLtaRQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHEyMURhQSBKQmY2
            azZUUXdSK1pkeTdQNGpRSG0rdjA0S0YvSjZ5QkhJeGh2Nk1STVhZCjgxUkFOSW5R
            SWZkQU5mczlYQzlWZWZjR0xBRER5MnRXRWFBY0xieEYzVFkKLS0tIG85Z0hUMnFY
            REwyVnZkNHhwRllRVzJMME9TT3ArUDJZcDFmWUNnalZYbm8KhpR9zPeA6fkymFo8
            8+pVSR10B0Wd9KgrrFCBL/NCa4ChqcssPVsBXviw+9/g4nv7fmYafWTm8I5mr0N6
            ezuCLA==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICBbJZYAoaiso9r80YdbBkqFZ1bggET4EEkzZ9ckBbGW
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHFodDFMQSBQdXlU
            QXlqWklrMVpZY0RwbXp1NzExR1Z6Z1JwYUM1Wm1CbUdXTkxPcEVJClJQMkd2aHE0
            aG5sUGV3Nk1ONm5KM3Q5bmNhRlAxTWNmdVJ4WlhFMkk5VzAKLS0tIE9JYU5NdkxG
            WE96TlE5anJDb2YweFYvRDF5eThFQmlVSTZ1OVlXVkJXRFUKMvA1mKsiJRijg38P
            MPDZmiBvgrWE9d0WwS1icHVJdl1cbqaCcdu+sFKyBvRBepBQJo5it8IHqRbSA7da
            CAcOIQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICvbJQ3KnO165S9pyfQ5qHXFv51cw3LmsvUn6Xo2Bbr7
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvOG1adTZKQ1hudHV0Ui9U
            T2Q1b0VsNFloM29UWVI1VVVWdVFJb1lEWGw0ClNQbThVdENtUTZGb1pqSUhnOWJD
            cHBIV2psK212Q3hvTzlzZXVBenJYQnMKLS0tIEJvb0grRjB5SFlRdWJsRVE3cWJO
            Z0VrZCtrNDJQTXdDbWtpOThaSFFWTEUKWhJob14MXT75pO9R5HFwoqH3cX0XSko7
            a/wqIkzggWOZEEy4XtrQYkJP6IspfXiY0j8ZaVk4+BVtIfRqXeE0hA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mnacljduxclddus4xa83h079w0yqz94h22kxwxjqj26vu6fg2ckqc3gymn
    encrypted_regex: ^(data|stringData|password|token|secret)$
    lastmodified: "2026-08-02T05:45:01Z"
    mac: ENC[AES256_GCM,data:8B6MsyUXLA1QZ3nPmv4i2Cio0Ci9nxIBc2a/HeiWoyl9U8xoO0CWxvw+0RTzt76XuQ7weILFrp69zvpcMLJSCWxRbXCoEr0Cy142Pp+H/1YvoFS6+s00K2tgBoEE341vFuDjBkO22ebY9gAwHPrIjavhQShbc1eOclRq0VNwXV4=,iv:1MBfR2taIA134BwIbRBh6HVvvdKcyiFI0FcAiT8EkjE=,tag:+2u8EezFyvsPhCgVKZWazw==,type:str]
    version: 3.13.1
