apiVersion: v1
kind: Secret
metadata:
    name: sammy-env
    namespace: openclaw
type: Opaque
stringData:
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:3n2KBtkJmRDLKFE2V5alPRHkYP8abSDicvkDIbrxBsLC9Da4qZTQtLFH+2corMbuMckDCgFoLWxVtYa6UX1wRLgU2Ag2AV0G,iv:7ZS4Qp82eB5YPDPA0RFBw+X5gFXSfq9aPsiWGv2QPck=,tag:+7V/hgivoXq2j9CVaMugTA==,type:str]
    GITEA_SERVER_URL: ENC[AES256_GCM,data:TTZ43JzkigDKsyvp7SN39IGBnnDUJDJS,iv:f+dYewNbcKTDzpZwW08R4Gg2fO9iydMEwORAPdMUwYU=,tag:sCgNiuMsXD6OFvLNcKksKA==,type:str]
    GITEA_SERVER_TOKEN: ENC[AES256_GCM,data:0G6qRrgER7LdiKAQYTVQEee14gTs9XiKtRSEpzbfzOCTFP2rc9aS8A==,iv:/TfqwBPVhI+Nu9BBIRkPbcmHmHXqSy0TMSHC0guPzlM=,tag:iJMwLLsS8Vv2ldAf0MKWoQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHEyMURhQSAyRTFV
            RFZRWkZwbnVPTlpFdzF2SHoxWnlwTVdValFRUHJCTnFZN1ptT3dZCnNlV2VYOWcy
            SmZHZDJFQlFKc2VWV0F5NWJnUGtiOEZIWUI5aUxTZlFjd00KLS0tIENEWnY5MzNW
            cHpZQzZTWG1PYU1uK1ZtYjdCZVZEUGU0M3M5OUJ0MU9pWncKFz7mPnAXa5XbT3kT
            e0eqv4Pd8qCtir5pE5JMhEAImmYj3nacq/olr+JsSYWiP8vGC7EERYB8rFT8DBtY
            eZ134w==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICBbJZYAoaiso9r80YdbBkqFZ1bggET4EEkzZ9ckBbGW
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHFodDFMQSBybDZn
            M3IrTkVMcWNRdUlEbXJzTVZ0NDg0emNUTlU4aEN6Y0lsaUYrM0VVCk1rNGtDTVBX
            UGk4dXk3bURmMEltcTdBR0ViOXBocUJsZ21qdmJJcXcyLzAKLS0tIHNzLzNpVTNl
            SmppbUhZY3AzZ2hkcmNBSExUWm1teUNLRkErR3JRenA3dE0K8Fz2PxdNdezVuQs1
            pBFSaR3D+5OdiDEljJsrMrSrd+mmnUFXIELfcZbYYp8N1k0COYlSFX5N0cepyO++
            kUV/WA==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICvbJQ3KnO165S9pyfQ5qHXFv51cw3LmsvUn6Xo2Bbr7
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUMDQvOWlVai9hWDk5Q21R
            UjVIQWE4dVZ2YWRTVnBLTExiL1ZlaytaYkdZCjVkZW8yMXFuSVk5MGFTeVFzTFQ4
            bEhVODBpTDVFM0xKUVprTkluSjI2eGsKLS0tIHM2cnlMenBmRUxjMitwalhsdnpo
            RzJSaXdxd2pNNXFONW1VTCtkdGt6MmcKA/oWiPcYKB87qdHgmwg/hf7J/L1FLxX1
            gLGT97Svn6JieGV0MiRwJlUe0Y1U8T/3Odbj11mXyxzjMP+zu87XPw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mnacljduxclddus4xa83h079w0yqz94h22kxwxjqj26vu6fg2ckqc3gymn
    encrypted_regex: ^(data|stringData|password|token|secret)$
    lastmodified: "2026-07-25T08:10:07Z"
    mac: ENC[AES256_GCM,data:ed8GoHxKnfrfBi9WrUrTNyyiHqOW95KgHbBfEDzV+hlORck97OOC1FBXHSeCYsc18od8hQg5oo0fm6ifIh96DMFPvWSaqWgbzdBls2vDzAxw8HW3VqB3+eFOS5fOeVxETDM7FqwKCgq/yO7c0+bVE1l/EhMwOlN4HdBxFpfcDkI=,iv:B6gEjLoyUN43GZVwXETjxjiRpbCb4W2fGuI//9QyPGs=,tag:hIc1wB1csWnmFUYF5PQqHA==,type:str]
    version: 3.13.1
