apiVersion: v1
kind: Secret
metadata:
    name: oidc-creds
    namespace: victoria-metrics
type: Opaque
stringData:
    AUTHENTIK_CLIENT_ID: ENC[AES256_GCM,data:rJ6P4zvHiv2AxHJ+yysEm9eRYSS/RYoU237Nn14VpoNQGqnmoiTtlw==,iv:Ws/5wyVKnlQ5vc04UouG9rS8S1+bHCTDLbsqKWG/DM8=,tag:2zpg70L9yJyXcksnNlE/fg==,type:str]
    AUTHENTIK_CLIENT_SECRET: ENC[AES256_GCM,data:V7aNKQ6PnUuH/uZ8nAwCYBWbCcNccxj0XMkk6rj+H70rIM0uVxn8tq9S6VUqcZ1EC8y/ayjZ214lPb0WbhCzzZmLaaFsM313aKkcXFJpG+/DQzhYDtF2Qrl0ezuxUzfV3H90rpNL0TzSlgqQB69daMX+aCekbd5mJjhgrkDR1g4=,iv:EABFkPNH3LOlyeqE4ZaVAchZQBxkkzwVjEolE1FJw6A=,tag:jGd+aSV3vcA/xuUtdvTzLQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHEyMURhQSAzYkdR
            N2ltMXpoTk9RUXFiakxzTGZJUjhHZUhaZ3pTMVBXVWlwL3ZJcjFFCmFMd2FXUEww
            OVFiVmZPKzZnSHhONHFaK0R0Q0dHN01rOXMrZ0xXTjlqa0EKLS0tIDB2TUxNclJv
            TmNCZ2VzbGhGeE5kYWRONWxwbE4wWVJZQWNXNXlYbVgvR28KRduzW80/JP5g9BCM
            UDKxCP7YOB8yeSIcml/lWtIxttFPVObecWPT84U3mxNbrrVSoeV0+PfOSvRBF2W0
            iLx+Bg==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICBbJZYAoaiso9r80YdbBkqFZ1bggET4EEkzZ9ckBbGW
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHFodDFMQSBiNkEy
            cHIrb0tQN01WMEtUOU81QkZhSHRKK0hBQ1loL01DSHV1dzFJSGg4CnhPQ0V0YWtk
            S2lSN2t3ajJIcFF4RG5SWWJFRFdHdnhiR2xiSXlFb2Eyam8KLS0tIGE4THR3VUpW
            WCtrZzVBUjV0MEVhUHFiUGZYZUlGSE1RL01yeEl3MldpNWMKgFsobCpIYz2RAtZv
            1VvRXP4VlrcUdqbndmeqshg75sWvPTW/3obCp2E/6U856oida8EnO9rDlsuaV6wY
            uGsSig==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICvbJQ3KnO165S9pyfQ5qHXFv51cw3LmsvUn6Xo2Bbr7
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVjN3aEJxc0tqaDlUUDJV
            NGhsSGlJelJBVVIzcHY1UC9sUHZvSXhxS2dJCkx0cTdDWGhORnlaamp6NkU2RGMy
            S0F0Zm14Z1JjNkJyYnFTMnVwRnJMTncKLS0tIHo5WXMyL1MwV0laYUtKTmFvdkpW
            N1hWV3k5L1I3VSsyT3RLMHZ0eHlMY1UKPjRel8Z3TByZ/JVt0uZik4hT5q6tt6NA
            rs3roCUfKPwILIGZCYRvrrAT1V5RN8JwtMmM5wcbUl8NBJwJAfe0dw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mnacljduxclddus4xa83h079w0yqz94h22kxwxjqj26vu6fg2ckqc3gymn
    encrypted_regex: ^(data|stringData|password|token|secret)$
    lastmodified: "2026-05-21T04:09:21Z"
    mac: ENC[AES256_GCM,data:Ao+YcRgyFZ9tUuR/dwy4kE0XqTmUsbCTPV2TnW4U2cuEzOqIt4trZauhFqXhhYIqLG+8ky5WFHj9YNNW79hRl4rEalb8NMGRMhSHG/i/RmuiskObSD8GQx+Hn4dbkvLxFhI+vAM9JiatZek1wwYhzdVht2KTQG7BJ7NdHNfq1sE=,iv:PKQyPTP9I4Vu2/ALuhAy/vV3At/t5TLc0VNFNMsufHs=,tag:uwz+kJYzV74fq+gs7oZABQ==,type:str]
    version: 3.13.0
