apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: victoria-metrics
  namespace: metrics
spec:
  interval: 1h
  url: https://victoriametrics.github.io/helm-charts/

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics-k8s-stack
  namespace: metrics
spec:
  interval: 15m0s
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      version: "0.76.x"
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics
        namespace: metrics
  values:
    vmagent:
      spec:
        externalLabels:
          Dum: "mmy"
    grafana:
      enabled: true
      sidecar:
        dashboards:
          enabled: true
          label: grafana_dashboard
          searchNamespace: ALL
        datasources:
          enabled: true
    prometheus:
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
