apiVersion: v1
kind: Secret
metadata:
    name: satisfactory-passwords
    namespace: satisfactory
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:RcOm6YIghOWsFyKpqrVnCdBNvRNwBQ4K7W2N172Cgp4=,iv:G+n+QVBLHsuTY2zHaMHMd8CQx2b3j5cpsTnJQLn6oDQ=,tag:yOXKbasVZ/QBGfC80dh/bw==,type:str]
    player-password: ENC[AES256_GCM,data:x3iGrVZbvvr7aZoFEgdl8AyOdbeRtanp,iv:FmoMkonv4BLKF0KEd3RnC3gQn/0+h1LRblp2YXahRyg=,tag:hOBeJ0kNuKs9/sfhn2uCJQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHEyMURhQSBtSVFZ
            dUNHOEpuVXBtdVRwRFB5OWkzOGc1QXIySk9hT2RwcW1NR253L1RvCk1OYWxWQ1Bz
            Uzhjay9XTW9yMG9jL012Y0tTNzJGY0VOZ1JRMzZjbG5DM2MKLS0tIEhGMWhBMFlk
            akYrUzZmdGdHT3pXRWpDM0dmOUdpNVpBN3MvKzQ3MTZpMmcKOAAalT3pISwkWp4R
            Uz15z4AaykbraUna/G4MqepzcarU9wjdmotS/yKobDfN8OldxIsrZeYC0fLbLWOA
            yeWy3g==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICBbJZYAoaiso9r80YdbBkqFZ1bggET4EEkzZ9ckBbGW
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHFodDFMQSBoaFJl
            TTdqc01yalRDaUVDVnV0K1IvaUlWWlhhOGc0TzRJZ2hsYTM4d1VRCitUaHRSY0Q0
            ODlDa2cvdUxYUTJ2TktSUjY0MjNUYmh5bFZvcmJuTmFRbHcKLS0tIGgzbThidjlP
            dnB2akdKbWw4Mi85alo1aWYwb3RaeHNVTlZma3ZGbDF4b1EK24pk3u90HZEC/JNx
            yKV5xhcku5Aqt0d1icOSigAKjF7cRBUCr6pf1HVWF1RJBZGu0VMY791GmG1LH04k
            4FVMMA==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICvbJQ3KnO165S9pyfQ5qHXFv51cw3LmsvUn6Xo2Bbr7
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ZWFLRmFjSEtoUEJiZ21R
            OTc4eDRaenorTk5zcWROZW5hUFBMeGJ5WEhjCkFiSTNrR2phK3FuclI0bGpMV0tY
            bDBjZmx6ZUFuQVhsTm1FSklHZ2xjcXMKLS0tIDV0YWIwaWFFSkxLYVIxNHdsRTYw
            UTZqeU9QeElxeXp3NDRqNDN6T2pycGsKw/LFMksAaBC5TftleacaA+hLfkoz5T2+
            amvF1T5PipoZCBdiE4uKzk163/qRRJVvgMNyNZqElIXuOQDDCvWsVg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mnacljduxclddus4xa83h079w0yqz94h22kxwxjqj26vu6fg2ckqc3gymn
    encrypted_regex: ^(data|stringData|password|token|secret)$
    lastmodified: "2026-10-01T05:46:55Z"
    mac: ENC[AES256_GCM,data:qm1ehi3EBCO35x722Iv2cr2DsCSbEWMsX0zkWXOPHL1IGct3QxDthailqF8UKv2/9ZaYe6VMFIMgsL3pHV1b28MM636qvS982LJuy2mn7fF2evtnD3J8wSbmesz5ECD9vzsXbbaW3cAQi9ULj+rJUsKeUzCcsVR8jt4l5bXY0Yk=,iv:D0dyw3yK6noXhxIw+6RQRlYGkIK45UKUQjnZVqHf4d0=,tag:ogLs3nD9fXVXTCXq2fX54Q==,type:str]
    version: 3.13.3
