apiVersion: garage.rajsingh.info/v1beta1
kind: GarageKey
metadata:
  name: matrix-media
  namespace: matrix
spec:
  clusterRef:
    name: garage-main-cluster
    namespace: garage-cluster
  name: matrix-media
  secretTemplate:
    name: matrix-s3
    accessKeyIdKey: S3_ACCESS_KEY_ID
    secretAccessKeyKey: S3_ACCESS_SECRET
    endpointKey: S3_ENDPOINT
    hostKey: S3_HOST
    schemeKey: S3_SCHEME
    includeEndpoint: true
    includeRegion: true
  bucketPermissions:
    - bucketRef:
        name: matrix-media
      read: true
      write: true
