apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - synapse-db-role.enc.yaml
  - runtime-secret.enc.yaml
  - database.yaml
  - bucket.yaml
  - garage-key.yaml
  - config.yaml
  - deployment.yaml
  - ingress.yaml
  - monitoring.yaml
