apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - synapse-db-role.enc.yaml
  - mas-db-role.enc.yaml
  - runtime-secret.enc.yaml
  - mas-runtime-secret.enc.yaml
  - oidc-secret.enc.yaml
  - rtc-secret.enc.yaml
  - database.yaml
  - bucket.yaml
  - garage-key.yaml
  - config.yaml
  - deployment.yaml
  - ingress.yaml
  - monitoring.yaml
  - dashboard.yaml
  - rtc-config.yaml
  - rtc-deployment.yaml
  - rtc-ingress.yaml
  - rtc-monitoring.yaml
  - mas-config.yaml
  - mas-deployment.yaml
  - mas-ingress.yaml
  - mas-monitoring.yaml
