apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: matrix
  namespace: matrix
spec:
  namespaceSelector:
    matchNames:
      - matrix
  selector:
    matchLabels:
      app: matrix
  podMetricsEndpoints:
    - port: synapse-metrics
      path: /_synapse/metrics
      interval: 30s
      relabelConfigs:
        - targetLabel: job
          replacement: matrix
