apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: matrix
  namespace: matrix
spec:
  selector:
    matchLabels:
      app: matrix
  podMetricsEndpoints:
    - port: synapse-metrics
      path: /_synapse/metrics
      interval: 30s
