apiVersion: v1
kind: Secret
metadata:
    name: matrix-oidc
    namespace: matrix
type: Opaque
stringData:
    AUTHENTIK_CLIENT_ID: ENC[AES256_GCM,data:MnsJL7XvPBckdwpgCsPAlNxvP/h4Kd6L4Xr/j8YdELeKL2XaSaTQxw==,iv:qLFptaEL95tTt4/HCc0B6xasM9wi5c/+V6vzisomyUo=,tag:zdBoqxWAyGC0wpukdt5+TA==,type:str]
    AUTHENTIK_CLIENT_SECRET: ENC[AES256_GCM,data:1QIIzAhNYvPKHxnEXhERM9XYCiE6A++9gtnHV4YEFQA8nCf4yKb/i2jtoo3t3gfHzaqGWcuDERNRLzmP53SCfMyyu6OCz5kqouAHdEZH8uvegjDJxP3U6eU5x9ssgx3u,iv:AynEMRuBiH99OC4ECCexuvuSIfCuCQ5XbdEpOh5pXmI=,tag:yVeZ5T6DNbwxqIuAefpWOQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHEyMURhQSBQY2dm
            Q0lBQnVYajVrYTRieS9kNXlrZGI0RUlQUnZTdC9Scm9sZE5wb2p3CkZrMW9GNTBH
            TktnTTBCMzJlYkkwTnM4NFNBb2FFNkpoSS9BTGY0UWlQck0KLS0tIEtGeHVxK2E3
            K0JtbnlQd0R2a2pQUi9PUklqWThNb2ZCR1hQWmI1SHBzNTQKy+vwZ5wPMXUhwAym
            7utuMry9BmALym7AMbvyQW15ULfYiJN6kJUXuLUq7Ltsm3Mx09dILzDBNjZ8KKRQ
            qhs0ng==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICBbJZYAoaiso9r80YdbBkqFZ1bggET4EEkzZ9ckBbGW
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHFodDFMQSBidjJy
            UVZOVEpNN0h0b0o3ZTJWTFl0Q3QwaVhySFNFZkNVeERUazJzbEJrCkg3QzBobW1U
            bUhVL0R2YlZBdVdocTVtRjN5VDNwZ3NmdjlDS244K21TVXMKLS0tIHY5TDNoM2da
            V1ZhaDB1TXU4djN0Zmo5VUtaMUxJMnBkQm9zaUdrOU1TYmMK1J/QDXFvJm2oZJ+H
            OyMi3hCLh4rb6H9JAw4WDLHqiAAEKKLD7jpGB5ElFB0h+WqsA+P/Tca5KMfCD1mp
            CQBBhQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICvbJQ3KnO165S9pyfQ5qHXFv51cw3LmsvUn6Xo2Bbr7
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSFYyVUdMdEFpYVdtWDcr
            d3ZyL00wazk2R0lhbDZoRFRFeUM1R1dLSWhVCitVREdsTituMmU5S0ZyMC9wYzdv
            djQ0TS9ETWhQTHBKNU1URUZkdWlRalUKLS0tIGlIbTVGZVJsaW8rWUxFSTFNbkNu
            VmpQOCs3MWZpN3M5YWczVWNOY1p3bUkKB7G3xhnC6mCmgc3Xnvde2gWqNWNsJwwz
            LnM8wW+Bkqsq0eAsSgAKGTDfrNXnsU3jgwPk/0Sl+PqiUuL04efuIQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mnacljduxclddus4xa83h079w0yqz94h22kxwxjqj26vu6fg2ckqc3gymn
    encrypted_regex: ^(data|stringData|password|token|secret)$
    lastmodified: "2026-07-29T03:04:00Z"
    mac: ENC[AES256_GCM,data:GOl1AZDv9LnnUvYeWqdRjbvshjTMaVb85DjRgIXQiHC57vqaa5d8swm70dy5FVMEonjn88X/biobCCuC76XR0lUqRbbxK83R8aH4NK7Yeinc7TL5Sqz431SV37lfspXNKCvKQ6FuRiotgBDt7kRF8jIPI4P4eAgHtCtM1L6wNpE=,iv:DyfXRuz7VkYqgF1SwZOJVkDbnFRJ2HpatjHMhzvyEJI=,tag:fdxdmUclRmjm4ra3OlruJg==,type:str]
    version: 3.13.3
