apiVersion: v1
kind: ConfigMap
metadata:
  name: matrix-rtc-config
  namespace: matrix
data:
  livekit.yaml: |
    port: 7880
    bind_addresses:
      - "0.0.0.0"

    rtc:
      tcp_port: 7881
      udp_port: 50000
      use_external_ip: false
      node_ip: 70.73.101.233

    prometheus:
      port: 6789

    room:
      auto_create: false
      empty_timeout: 300
      departure_timeout: 60
      max_participants: 12

    keys:
      replaced-by-init-container: replaced-by-init-container

    webhook:
      api_key: replaced-by-init-container
      urls:
        - http://matrix-rtc-jwt:8080/sfu_webhook

    logging:
      level: info
      pion_level: warn
      json: true
