apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: matrix-rtc
  namespace: matrix
spec:
  namespaceSelector:
    matchNames:
      - matrix
  selector:
    matchLabels:
      app: matrix-rtc
      component: livekit
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      relabelConfigs:
        - targetLabel: job
          replacement: matrix-rtc
