apiVersion: v1
kind: Secret
metadata:
    name: matrix-rtc
    namespace: matrix
type: Opaque
stringData:
    LIVEKIT_KEY: ENC[AES256_GCM,data:kDdxUbXmMcDWljruo/ojmKRyrP4=,iv:t/nwpIged2xUl/5Gsg/enNJQqorgPxAIJ0ThLAiYo5U=,tag:cgUTi9QgksjXrpNTjngQCQ==,type:str]
    LIVEKIT_SECRET: ENC[AES256_GCM,data:zcj6vxNNpecLxHUek/2Qa079/5U5v4Nmymd0RV5bNgY/3s1co80vzVCBe25PcYv+6Ob3ZAc3GA+yII0qct05Nw==,iv:SYtINAuihhf+SqlLWTT5a4irgqVLTD48MGO72G/zBrU=,tag:oWhAArSh1CVk6bHwuaknZw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHEyMURhQSB4dURx
            T2xyRkxBMUdZcjkyZWpRR2RTUlFnaTBWMDNnR1pyYVRhVlRGQ0RzClRKUE5jVmds
            dmVSVjkwTXlJSXI0SzlIRm1IaFNYd29BL1VlMTBDaEZPV3MKLS0tIG5rYk8wT3RR
            V21GdUkwNWZKYkVMWm40clZiR1ZSb1poSjFUUkxITnpqLzQK4sfrjuNYqMIkWeyi
            ne8o+0bPSgh97cXttbfss/xuklJ8M1IZHHaxmJt8UVnWwmi9NmeEsrnW9UHfCbKo
            HHS8ag==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICBbJZYAoaiso9r80YdbBkqFZ1bggET4EEkzZ9ckBbGW
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHFodDFMQSBmb2hZ
            c0hPSEp5aExvbUZtcEtCQ1hka055OTRDQTB2cWFTbTc3d1Y1eEVjCnVkSXNoZTYy
            NksxSEF0aTI0R1oxanhacU9IRGxtalFtakZEajZUT2lSaGcKLS0tIGVwZ1NaSkJB
            UXdMTzBMRitaa29TVWFXVWJIMzJrOUZJQXlSR2M0b1M2MmMKbgizUeL855zcDX+F
            wkXuOKxU7dmNOqmH/N2wkjE3+zUud0fr8kB8rBFCSqebvOEXLzZpgxqWcMlMTwEG
            Ag/V7w==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICvbJQ3KnO165S9pyfQ5qHXFv51cw3LmsvUn6Xo2Bbr7
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5b0MxM2V5d2kwaWJ3MWty
            N2kxUDlZMExFbmRKRmQ0SEJ1WndFc2UxaG1FClRaSDl6Z3lTTUtZY2NhWVM3WTk3
            S2hpLzQ0L1Z2dTlacmhnKy9vZ3laRkUKLS0tIFNFRWp0MzNIT1pBVTB0bDQvMlYv
            ZTZobm5nMUY5UEdFWUpmZ3BTdWRJMDgKdPbT7L0JrX3LzptToTVRqgCY+2R77tNQ
            gernhWvYO8oje5ppxcsuUIoX3tQ5/q2UFzLZkEOZw5laf7QH0F6UDA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mnacljduxclddus4xa83h079w0yqz94h22kxwxjqj26vu6fg2ckqc3gymn
    encrypted_regex: ^(data|stringData|password|token|secret)$
    lastmodified: "2026-07-31T01:53:51Z"
    mac: ENC[AES256_GCM,data:AyKaSsW/2zB4kd0+ikmiP0UYOl20H9kzmTmi8vYDpOSZz/Q5s0nrrnIELUse5oluMz3a0WCJVpkS9U+Vw+iUV8fSQOU4LPCy7RDDsFMY9/CjSwtHgfTM4aBSrv/A1k8WgrKMA0H63HE+eUHlglETqy9J6U/GjdoUIbIrwx7plCw=,iv:A4uqLQP2hH1DtFgvANBl+9Fd3p3WzDVy96K+VtnMVu0=,tag:zF7gg9Kkjs0KhCHLLW6z6Q==,type:str]
    version: 3.13.3
