apiVersion: v1
kind: Secret
metadata:
    name: matrix-runtime
    namespace: matrix
type: Opaque
stringData:
    SYNAPSE_DB_PASSWORD: ENC[AES256_GCM,data:9XC+gSF66f+85VAJaOvx5Lr48m3K5iXqG7YtvOdXhwKRuZGf7l3wJ67veQ/jm4QhpS8VQrUp9TpMzmMKBBSnUg==,iv:OGaEnTs3ypTe1us7B2ZPd86seJUl9mt+Gba5YBqKCZI=,tag:9y/fSdZi69cJYs0iwzRvTw==,type:str]
    REGISTRATION_SHARED_SECRET: ENC[AES256_GCM,data:xCSIyZzMlutp6cA1rNe07DO0nGzF3UbTd3MEF7/17zVqjA79qBA6pjl/ry6Gtox2qCSyeCb1Ax905qi4Vrmrdg==,iv:edwcL1l1VWGubjU0tPKFZVwg3ToeBf44gbTp7gv47mc=,tag:ElcLMMOLv743GJXpL+SePA==,type:str]
    MACAROON_SECRET_KEY: ENC[AES256_GCM,data:p3WBzL5os/BI5Ydx/KCFe0hVIrlUaglJ8rJkPP8A0+0DQaroaPRNJDXxGJI/4bOuk7RmJwJwZY9zNdI8cbnZQg==,iv:E7Iuo2TCuc+wA8fWoyD67E0LV7vrvxj7kz7zTNGaFGE=,tag:0YBWQfDRe82OO1fjAQMgoQ==,type:str]
    FORM_SECRET: ENC[AES256_GCM,data:QpeWQstxRj3iovSVq1HsdAkrNkfAdmqSIHFTl76yEj0hhE/wyDnQBM0HzN3ngUbHWnwOIRqEatjQGSjbZzIk7Q==,iv:BJd/EuMU7zuYzWPMoEgtJD/ETTbgd46FazRFz+leugE=,tag:qKPl4QsyeUe/idJZ6f7Xpw==,type:str]
    signing.key: ENC[AES256_GCM,data:DZmlKi1yABO1oFcpU2q6lUDI6d+ZwDnWZBCCTHfY1zYpH7gy57WsIfdNZWCYMFkcL2zs3ossmQ==,iv:p8c22TYNUaX8Y14b4XFz3i0FjJdNM0mmOziChzzluvA=,tag:VNNZJwDam25krCmzooij+A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHEyMURhQSA5eWI1
            eDAwUzhvck54YVlEVldTYjJxMWlGVVlYWHdjSEtnbnZDWTRwMjFnCjlKMERQait3
            eHpzN1FmV25vWTJYUGU1QVlGRGc4U1RSR2swNzQzMXVua1EKLS0tIFNjWmJ2MGtj
            d05FRVJxSDNYeDZZMUJyOG0va2Z6RE5yaUFzUnBVMVRJU3cK6tbkzDyr4x7udRcA
            zdkWyoYwtry0H+/nyPRNZiSEVbv/PjIiQ3KWrlHFN9rv0B6bqe3rg1HjDjKpA0Tp
            yPW0QA==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICBbJZYAoaiso9r80YdbBkqFZ1bggET4EEkzZ9ckBbGW
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHFodDFMQSAvbkF1
            TVN3N0tzY0ZMTnVOT1VZUkJOTTdjZm5PLzRORlo3L0JWRjFsNEd3CjVUUUx6eHln
            MThld0orU1Q2aGx5ZXV2TDZxLzc4QzhVSlBwbEl4QW83SVUKLS0tIDM3ZVlTTHl3
            OHN5L2NDOGJpT200SGQzMXl5UFJSUHJVRTEzTzRmUXdHaVUKDaQ7A86oc6h51jJ3
            XPBdwHGbs7wYg3RzmhmZ1JQasZ8ogyGNfkkDzLwDJwRhUNTPwEr3IFuS2/kFylbI
            bEUI+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICvbJQ3KnO165S9pyfQ5qHXFv51cw3LmsvUn6Xo2Bbr7
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkaUVDVGV0bDF6dGtjUXZl
            ZkJmWjZ4UnhoK2NFcWtnRFNJNkE3aG00clR3Cm9xZzJJRmdYVzZWWk1CN3E1djUz
            MmZaT2g1N0duRnhGSS91OFR1cVhpcG8KLS0tIHp6ZllucG0rd0Nxdk53N3VaYVM1
            ZDNzUzZrT1EyWmt4T2hqUGN0cXNESGcK2Z+1PIXyhP/VIfthUSXkIVY4L4l6d2Eh
            Rht+kk8IvAPPYoohYEPfdij5qhlvAxpy8IkSBoUqB1uFYHtr1W80yw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mnacljduxclddus4xa83h079w0yqz94h22kxwxjqj26vu6fg2ckqc3gymn
    encrypted_regex: ^(data|stringData|password|token|secret)$
    lastmodified: "2026-07-29T02:42:05Z"
    mac: ENC[AES256_GCM,data:ij/bW+GuSDMg2vV3QFo+g5uoaOzW4WnQmkugEx2garc8OBCQNUNfV4T3yvRdcCRg6bn10TADq3DIt9F31gCj6mMEwAWgrgb6cBrGC5WSRBsYaYxJLme+m4zbypAut5ZU0KYwQcDSUFT4zk6ozVpZ0EpsqJhj/ZMpIryF7yGszTQ=,iv:uaEqTVaKDh8Y+TmUhCWwHTwJ8pdPI6OoHL4fSIjd0NE=,tag:2GVohJ8U7+Q3tp6Udhi+Kw==,type:str]
    version: 3.13.3
