apiVersion: v1
kind: Secret
metadata:
    name: forgejo-admin
    namespace: forgejo
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:S2wjP4w=,iv:otKBCr9MzU8ZrXrxtvXKtml35TsmvgxtFLYH2jqV1UU=,tag:gCE8FQAAmYo3Rs+vJ960EQ==,type:str]
    password: ENC[AES256_GCM,data:8Jg0pE0NRUY=,iv:u8YrIm1PDmmWh8jc3LvL4OEJKCzd6lqI69Tkpb/ptZo=,tag:udWRF6FGhpP7i22LpaX/BA==,type:str]
    passwordMode: ENC[AES256_GCM,data:/eiDjiW+Rn9pTLQ=,iv:Igc2d5xy0X7Va2ajCRvE1NmxAdv368l3TWsO6biMVG4=,tag:Dm+6stHGZgFPWGUBerECZg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHEyMURhQSBRZnFV
            aTN1dEQ2RzloVURVTEcvUkxxOVptc0RyUFBDUTdoa082RkpFVmdrCmh1N2t6a0dY
            MDZtMVM2SGFwT2c0S0JWcnRpSDU4UnczbDh2UnFVcUtKUkUKLS0tIDI5WDRqUjlN
            TGlEbEprTlJKY25Fb3llRVE4QW5wcTlhYmlCcXdybEphK0EKFA0jFJqFUk+gsGoQ
            1Mfn2iVFI3NGMQi5H5vAcVypf53GbrLHuj/y31ldph5Dp016sqnzu5P3/KW/oYSC
            OF53LA==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICBbJZYAoaiso9r80YdbBkqFZ1bggET4EEkzZ9ckBbGW
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHFodDFMQSBuejBF
            NHJTREFYZndIS0l5Si92REhtdjFxblp0TEZwd3dWNUNRV2dtaXhvCjFnSGFwK3hh
            cWJXamZDaHk3WmJMTncweVQ0cHFvbHp0eEZKOTNSVnArL2sKLS0tIC9WMzhtMGZm
            Y0ZDUThXbFV2ck0vdDVLVVlGa3NqS0s2MDVoY2duQUJRbDgK5yvHSuDxLyo3JGR4
            3YySzB4HpFYZMKoHz4kuZvxgQ/MK9Yj8kLC6HBz7WUht05RCgnbmAQZR6f5/9bTl
            GxbPAA==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICvbJQ3KnO165S9pyfQ5qHXFv51cw3LmsvUn6Xo2Bbr7
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTXYxeXJWOUMxV1BxV1J1
            MHF3ZDQ5THg4QXNMclY1M21OeklHYUlyN2p3Ckp0RDlCU2doRVRVNWxqdUpUc3NY
            aHNIQWJQWG8wR1NDZSsvVW9qU21SUWsKLS0tIDRlS1lCVkZ0cmRweEhRaEN0ODBa
            czgrWVFNVUM2M1lwOGpRWk9YVmdYT2MKVfCEdIV6nIRJcKLNcxqdReHSeQ7X1H1a
            9phIaSfsYq2k6/UJ+xc79fxcNujL71nFmI8+hlSgBRczbEykXVCvTA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mnacljduxclddus4xa83h079w0yqz94h22kxwxjqj26vu6fg2ckqc3gymn
    encrypted_regex: ^(data|stringData|password|token|secret)$
    lastmodified: "2026-05-17T22:31:32Z"
    mac: ENC[AES256_GCM,data:iARq5SEYH45cc2kIzihnQvZuUpt4MbvHfhFU990l57YIZ/7swoLGjB7o1VTdEzMIq1h7/igo+V16LrhSHHQM2evNHxo+yU34s6lnokUsCCYaziFTzE6VI1mfWRe2z/vznkGtBvNeTOjtcr+8VudPGNZkPFb3yCl+lgHfGbK2JFY=,iv:R0DOowqqh1f46atxZ98T+q7siNJxMG21Od5bRsBatYw=,tag:1URHvu5YuKLdO75cptn8Uw==,type:str]
    version: 3.13.0
