apiVersion: v1
kind: Secret
metadata:
    name: forgejo-db-creds
    namespace: forgejo
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:KQomcOKjGJolab7EUuksrlIyBedit/PljtCf17rNFURYqwJQWqEtfhS/6DWcyfCy5580BmFJgeK50CQocClN+8B4/W7ECAaoO0b5BPG7plQHkWvAJqsWWha4dAhs6jiGzOSen4Y2rP1oyiu2Iwb3X5lGdv9tShiXF1QJOZ5t7hcAjh1pepXcy+M4BMNKfoF6L4d3OF+ewcfUEfcy3t+GfC+aNzbRZZc9CeIYae08ldd3QCyg9NtAP1G/Vu2sZd5wHUzwYQeWZCdT3JNEKk7wYv6eX3hrCAmzUWtLAisGgePQcl9SQ5Ippd5nQ3EMqHPJibuLhDcQen+JJN8VCcQdEtQI5djpoJ0CHbKelTBnrGqK+9IGVMuqLd6V8hcYIWqR9PIPb4p0/LAWBmXeu8x/hs/q,iv:7FqsLzyQ41XEIbZc4HdiJhyRFJ2s7Bxa8PALBaEHF7Y=,tag:rOfWgINvzqbx9F+ajNY6lw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHEyMURhQSBwRHlM
            MzRBcTNyNXFZalZ0MVphVlIvVU1kY05WUnRtWjdFZjRVMHVPS3hzCjF6R2J0R3FN
            K3BwY0Y1dFV1NGZCUHRvMlNqSHE0anU4ZlA4R2Jqa0E2YTAKLS0tIGRiQW8zSEUx
            Z3kwSGFkeGNYWDB6cld2YVNaam1SbU9adnpPS1dTVUxXdXcKprQTtQh9A8YFzv0L
            Jps9/vnNYnAlCRowaH3YtOaVCbD7t7Rj56uUBgx/YRbhMBLI6cNuKQ2rbRNVajc0
            /LyHdQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICBbJZYAoaiso9r80YdbBkqFZ1bggET4EEkzZ9ckBbGW
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHFodDFMQSBld0RQ
            Mk50OU5JT25CWG1ONFczQU5yeEFYYWhiYzFvM01QdzhhQ1RGcWd3CmM5SElKZmpz
            S1NBTUhJTDFQMGpEc3ZFUHA0bGhmVmxiQW9oYU5NbjI5STAKLS0tIG5tSXdEK1JL
            ZVluL1IxMnhRa1N0RTIzV3Y0ZVpzcE1jdkRwNGl3cHJUY2MKUNmvytHT6VKaNRXB
            bqdASeNTdab0qRG1aD9NUtWl8VypvU9fCjtRNy4MtIGeqF2/dtAcOu+QaHbAcv8o
            T2iWng==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICvbJQ3KnO165S9pyfQ5qHXFv51cw3LmsvUn6Xo2Bbr7
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsYXdYUVc1NXJiemRHMkZG
            VHVDWTRqNXJ6Q090V0dEQkJXQXRmc3NYNFJvCmN6aDVPZnhnUllTemZ5UjUwOGJn
            anhPOXNUVmpnVEE4T0t5MFFHYmI0NXcKLS0tIGNFazJRRVRkUGROSjJqTGNmM0Q4
            RjVGY0V5N21KTFhsVmJmeWl2bEMvdXcKvWgSGh0bYlFoMLqYXXECh1WwB/9NwkMJ
            42QjedGkqt7X4Qc5AfMNvWj25z2veq3DJmqh2DsbnD2vFBHDu1TLlA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mnacljduxclddus4xa83h079w0yqz94h22kxwxjqj26vu6fg2ckqc3gymn
    encrypted_regex: ^(data|stringData|password|token|secret)$
    lastmodified: "2026-06-12T22:06:39Z"
    mac: ENC[AES256_GCM,data:74wPDVZTkYwdH3IGexnUqkQYQqDqt7tCX/7tH8sDsuqAc22E0m85W9C+QGcNzKaYAJIEfuYtjKC6mB8e/8Ujrf5Pn1RRDJTBYx27nx4wu8o4I6sLOkqxiMLq7MRC7Ao0VrH6S6ndywVz8mhGYiOmfQOnckyEyIQM/fxejxkbgl8=,iv:FCD7IODVZzt1AY+xaUr5t6mYJYDgpR2MxIt+Fy7HMAE=,tag:+06a6pKhn0u2S/xGsq/dVw==,type:str]
    version: 3.13.1
