apiVersion: v1
kind: Secret
metadata:
    name: forgejo-db-creds
    namespace: forgejo
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:83dssicRULuJ3ewpC22myj7mDHc8C1BzCL0V7D1FwFk7vadcBw2EZO/kfueIwMg+4gaIEMWn3cK05ocm1eojTvte/dzQ7PIHcXF6Y38hUldZoGT/tS4PlAX1G9SjGKx5Y9TRB08djkICJAjey7qj8CbfJO1dPdsFUNTZXFcjuWI96W3KQoi0Zf7xepLi8XIe1g8ELskQqlgKBd0HHO600fXNfAxwAOcNuNA9OlaXxebncsuvfVUYI/zOL2W0Xp7y48GcQePiBGk0kcqJawTFzBshPqYTbNmtheh4cM7Z5/xQScN7bhcxwQCh5xYFAlL7cMoxk5mIZqsRn5abKhR2wRmiro8RJnU3nb/t2CbjqfXo8FN60+TGmrqQxvh7e63vC0uT4TcANgp8jfjj5VDiV8QPFYS1g4vrC80WBFHrWQw4Tgbjj1Sg32ZGNEsJMrzHXuI9T4nsXnw7iTLgtg==,iv:mC0SvWiOdcgVGHf902klPEJqr1kv67z/5ITI29TcA/A=,tag:szauQZbGSC31QbK3QaCp4w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHEyMURhQSBwRHlM
            MzRBcTNyNXFZalZ0MVphVlIvVU1kY05WUnRtWjdFZjRVMHVPS3hzCjF6R2J0R3FN
            K3BwY0Y1dFV1NGZCUHRvMlNqSHE0anU4ZlA4R2Jqa0E2YTAKLS0tIGRiQW8zSEUx
            Z3kwSGFkeGNYWDB6cld2YVNaam1SbU9adnpPS1dTVUxXdXcKprQTtQh9A8YFzv0L
            Jps9/vnNYnAlCRowaH3YtOaVCbD7t7Rj56uUBgx/YRbhMBLI6cNuKQ2rbRNVajc0
            /LyHdQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICBbJZYAoaiso9r80YdbBkqFZ1bggET4EEkzZ9ckBbGW
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHFodDFMQSBld0RQ
            Mk50OU5JT25CWG1ONFczQU5yeEFYYWhiYzFvM01QdzhhQ1RGcWd3CmM5SElKZmpz
            S1NBTUhJTDFQMGpEc3ZFUHA0bGhmVmxiQW9oYU5NbjI5STAKLS0tIG5tSXdEK1JL
            ZVluL1IxMnhRa1N0RTIzV3Y0ZVpzcE1jdkRwNGl3cHJUY2MKUNmvytHT6VKaNRXB
            bqdASeNTdab0qRG1aD9NUtWl8VypvU9fCjtRNy4MtIGeqF2/dtAcOu+QaHbAcv8o
            T2iWng==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICvbJQ3KnO165S9pyfQ5qHXFv51cw3LmsvUn6Xo2Bbr7
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsYXdYUVc1NXJiemRHMkZG
            VHVDWTRqNXJ6Q090V0dEQkJXQXRmc3NYNFJvCmN6aDVPZnhnUllTemZ5UjUwOGJn
            anhPOXNUVmpnVEE4T0t5MFFHYmI0NXcKLS0tIGNFazJRRVRkUGROSjJqTGNmM0Q4
            RjVGY0V5N21KTFhsVmJmeWl2bEMvdXcKvWgSGh0bYlFoMLqYXXECh1WwB/9NwkMJ
            42QjedGkqt7X4Qc5AfMNvWj25z2veq3DJmqh2DsbnD2vFBHDu1TLlA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mnacljduxclddus4xa83h079w0yqz94h22kxwxjqj26vu6fg2ckqc3gymn
    encrypted_regex: ^(data|stringData|password|token|secret)$
    lastmodified: "2026-07-28T01:21:16Z"
    mac: ENC[AES256_GCM,data:YajcANO7h3Uv/+yWELCzSUnCDlqP/ZpOpI0HTXgFyhEff8r99rsBNdg676fAQbA+7Nt0eKM+h9CCaO2jaA4z6IDLQQiO2+3Kjy5tKHVWXyxz692md5ktOyl66b4qvv6ghvKkdNHhYGjTXaNXRMFHCs0Lu5CIeeoS57oTsrsa36c=,iv:yhxS7aZGPAnEmrsxNYn3D1DjTp3tztdiaiJ9nVm7B4w=,tag:Uem3fFGFxcJJsACUypColA==,type:str]
    version: 3.13.1
