apiVersion: v1
kind: Secret
metadata:
    name: forgejo-db-role
    namespace: postgres
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:vlN+TZCIbQ==,iv:0/epTcXiHXP/rMmae43I67pLmGp2eZiz0ir20wjE+Co=,tag:LDTbYbhe7xwqWiOnivoAGg==,type:str]
    password: ENC[AES256_GCM,data:ZEkUrqyacRzLInHncsk4y0JiGYGVsedqVSjJdpfx0YIanClZMm4XxvnJAW1ZmP9ec0yJH75LT+6a5RbEQgS+EA==,iv:KZBSs0Nj0IUUPVPzeVrM0w8r+YJxrNAXVnImkA5IS8M=,tag:xQOWaz/5m7n5K0yplWzr1Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHEyMURhQSAzVXVr
            UXBNRGlJNDN3bWZYN0dwekE0VXNKZ2xQeDBUUVo4YVFpNUVYeVRzCmNldkcvc3Q2
            c1ZaMWhpbXRQSjVtWFRqRksyYVBodU0waW16alloWGZkMTQKLS0tIHBmTjFzV3dw
            d2w1bWxhaUlyQ3UvNGI3d1Rtbm9EM2R1dGpqdm0vcDZaNUEK9mQV6XX0eAwovXu+
            Oz0QbPUkaluK9TlnicSyTGrMVquOmHrYzYb29p0ZjyBff3u2wvAZXe7GXmXIneug
            6LtBJA==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICBbJZYAoaiso9r80YdbBkqFZ1bggET4EEkzZ9ckBbGW
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHFodDFMQSBYVzV5
            U2d4M3hnWThMbmxsK21LYlFuV01jcFFkdVhTWXNQSG9Nbk13QzNrCkM3bFRaNGFS
            K2JtdGRVZHFzZ2RmZU1IdmhYVHhGSlkwak1JZUZUWmlyQnMKLS0tIEtlU1YwNEoy
            UWFrRG56V2JiSElVRjVIRkJoV0R1dmVXQ0ZaVlNaeTlVTjgKHC7+1oCHfgF6PsWW
            Xlcxr4OQwlz9HnZlxlfFIkHNomfg4vjORfarEaze0k5i1SZ26hOOegbeTBeZ//JI
            WkthYg==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICvbJQ3KnO165S9pyfQ5qHXFv51cw3LmsvUn6Xo2Bbr7
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOFN4bHQzQThWMks3a1pE
            S3ExYWY2UTRDSWUrck4wanJBcUNHMXM4dFdFCjA0b25rVEdPd0VkV3I5VjJ1MWVL
            dDh1TFBZNThhMGhVYnE2bVV3dERKQ3MKLS0tIGV5Z0dkY3hhOWdqelNiYmtYRVFR
            bjFta3RjeHkzeUZzSDlqZjlPeVJDWjAKjqlTsbHjeo5Tv6S6xOqQGnZvUfYEQCw4
            3XmPGIYh33FYFuuhSfDJpaLw5JkvEFgDBHgizPDCuWR0K7dw/JsVvw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mnacljduxclddus4xa83h079w0yqz94h22kxwxjqj26vu6fg2ckqc3gymn
    encrypted_regex: ^(data|stringData|password|token|secret)$
    lastmodified: "2026-07-28T01:21:15Z"
    mac: ENC[AES256_GCM,data:7l2xrHkR1/cdZDcui2K8B0uWUjeiGruT00pdPgDlIWBEw58uBPKkN4kU6fHo9q7MDEHD/hFtJwfX5nJoGycqWruWHIGccCpa/izdBdFEoI8fcqInUhQOhRX5WonM6KqJDwawcj4aIXpy50idY8/70Jijs4VYTE1Tb8ShYqXBqIc=,iv:VtjWSUHRgQ8jmFP2lHXlfPjp+UMRm6V5bXNSkz3BF9M=,tag:ge6rFP48nHqey/RYNswmbQ==,type:str]
    version: 3.13.1
