apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: forgejo
  namespace: forgejo
spec:
  interval: 15m0s
  url: oci://code.forgejo.org/forgejo-helm
  type: oci
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
  namespace: forgejo
spec:
  chart:
    spec:
      chart: forgejo
      version: "17.1.x"
      sourceRef:
        kind: HelmRepository
        name: forgejo
        namespace: forgejo
  interval: 15m0s
  valuesFrom:
    - kind: Secret
      name: forgejo-db-creds
      valuesKey: values.yaml
  values:
    image:
      rootless: true
    service:
      ssh:
        type: LoadBalancer

    resources: {}
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      # requests:
      #   cpu: 100m
      #   memory: 128Mi

    replicaCount: 1

    persistence:
      enabled: true
      create: true
      claimName: forgejo
      size: 10Gi
      accessModes:
        - ReadWriteOnce
      storageClass: longhorn

    gitea:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      admin:
        existingSecret: forgejo-admin
      config:
        APP_NAME: "A Forgejo instance from Sammy"
        APP_SLOGAN: "Hosting some of my shitty OSS"
        server:
          #LANDING_PAGE: "explore"
          ROOT_URL: "https://forgejo.maio-tech.com/"
          DOMAIN: "git.forgejo.maio-tech.com"
          SSH_DOMAIN: "git.forgejo.maio-tech.com"
          LFS_START_SERVER: true
        storage:
          STORAGE_TYPE: minio
          SERVE_DIRECT: true
          MINIO_ENDPOINT: "s3.svc.maio-tech.com:443"
          MINIO_BUCKET: "forgejo"
          MINIO_USE_SSL: true
        service:
          DISABLE_REGISTRATION: false
          ENABLE_INTERNAL_SIGNIN: false
          ENABLE_BASIC_AUTHENTICATION: false
          ALLOW_ONLY_EXTERNAL_REGISTRATION: true
        session:
          PROVIDER: db
        cache:
          ADAPTER: twoqueue
          HOST: '{"size":100, "recent_ratio":0.25, "ghost_ratio":0.5}'
        oauth2_client:
          ACCOUNT_LINKING: auto
          ENABLE_AUTO_REGISTRATION: true
          USERNAME: nickname
        repository:
          DEFAULT_BRANCH: "main"
          DISABLE_HTTP_GIT: false
          MAX_CREATION_LIMIT: 0
          ALLOW_FORK_WITHOUT_MAXIMUM_LIMIT: true
        metrics:
          ENABLED: true
          ENABLED_ISSUE_BY_LABEL: true
          ENABLED_ISSUE_BY_REPOSITORY: true
        admin:
          DISABLE_REGULAR_ORG_CREATION: true
          USER_DISABLED_FEATURES: "deletion, manage_password"
        log:
          LEVEL: Warn

      additionalConfigFromEnvs:
        - name: FORGEJO__STORAGE__MINIO_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: forgejo-s3-creds
              key: FORGEJO__STORAGE__MINIO_ACCESS_KEY_ID

        - name: FORGEJO__STORAGE__MINIO_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: forgejo-s3-creds
              key: FORGEJO__STORAGE__MINIO_SECRET_ACCESS_KEY

        - name: FORGEJO__STORAGE__MINIO_LOCATION
          valueFrom:
            secretKeyRef:
              name: forgejo-s3-creds
              key: FORGEJO__STORAGE__MINIO_LOCATION

    livenessProbe:
      enabled: true
      tcpSocket:
        port: http
      initialDelaySeconds: 100
      timeoutSeconds: 1
      periodSeconds: 30
      successThreshold: 1
      failureThreshold: 10

    readinessProbe:
      enabled: true
      httpGet:
        path: /api/healthz
        port: http
      initialDelaySeconds: 0
      timeoutSeconds: 1
      periodSeconds: 5
      successThreshold: 1
      failureThreshold: 3

    startupProbe:
      enabled: true
      tcpSocket:
        port: http
      initialDelaySeconds: 1
      timeoutSeconds: 1
      periodSeconds: 2
      successThreshold: 1
      failureThreshold: 75

      # If you are looking for Auth/OAuth/Oidc its defined in the ui
