apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: public-internet-only
  namespace: forgejo
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/managed-by: forgejo-runner
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53

      # Forgejo
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: forgejo
      ports:
        - protocol: TCP
          port: 3000

      # Forgejo runner manager
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: forgejo-runner
      ports:
        - protocol: TCP
          port: 42503

      # Allow all exept cluster
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.42.0.0/16
              - 10.43.0.0/16
