apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-secret
    namespace: forgejo
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:70XZMKgeANEJ1UgFS0vHW/zOEK6Ysc9uD3zrX1Pci+FbPCSLcoL23Q==,iv:1jMIB+cu4kkyCaeq7M1X3VPKlvNZ8z8ii04BngtQbyg=,tag:IxdCq5Gi9kfvBoJzdOszCQ==,type:str]
    uuid: ENC[AES256_GCM,data:ukhHUkeA/JV8fQCj6dGfWC+LsIyjoN+/IUlQ5ah2xRPOHAGe,iv:i1S0DaTDZRKgzT71WzniAD2+khR7PIP3bUyk9T5cgvA=,tag:1B/zvyQgvj/RWeZQzD7Iqg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHEyMURhQSB1VVNx
            UG54NFhtUWRsNXI0MGc5YkpnWmZxMmg0aDVvWnU3Unl0eHBFSFcwCjBYVXRpQWRl
            eEJkSFdFM1ZpSWpuNEhYN1ZCTU5NRnFuTjlwMndXRy83K1kKLS0tIFBjQ2loVVJD
            anVxMzVRa0txNTBVYmpGbmwxOWJUa21OT1ozNS8vd2ozYVUKGIfe33G3tG08dibT
            y/ZDC02Ikxd6GfXHfNl7uNin/mM9H8Y4UqCSlE2N5jImM6xpTdR709jL7MxJztsE
            OxteXg==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICBbJZYAoaiso9r80YdbBkqFZ1bggET4EEkzZ9ckBbGW
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHFodDFMQSA0SUJX
            UlNEdVlrVmcvR1UyQmptQjZDMldTSWtpbnEvN3F0UnZnSndxU0cwCi9xRDc5MEVk
            MnJRN0RiWjY2ZzROUCtvbkRMdlpVZEJZbU1jR1hlZXdvOG8KLS0tIFFHdWM1UUww
            TG5hQ3VNYzhpYU1NZXFSajByNUNhVnRKd1F5bkU2azJpclEKVP+t4gKjrmKedKTM
            8MpHAj8xIGRgqxmo3ni3/+ObgJNrbw56vGGZGZ+FXqHmlbkguzsD3TBwVVVmsai8
            +gfZgg==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICvbJQ3KnO165S9pyfQ5qHXFv51cw3LmsvUn6Xo2Bbr7
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiajdRaWpET09EenpxM1dM
            YUlxbTBKTkpTSWl1ME1mS0dCRVdManhFYmlvCkt4NGs5VUxYbUsvNUYxQVRQaXE0
            cnB1ZW5ZRytqY3dtVGFST2VzWjIvZDgKLS0tIGUrWlBtZFFrK3F4T0R5aHFXOHRJ
            SXBhb2NEeE51emxGQW55TGdJalRBQUUKdBOpwYAMzos+0FtfGS16oo2wl8bXrzHL
            r/kVeVvVMr1HXG3ug9bdXRIZuPSXWJDSOYopGv40WX6CHyKtLFx2fQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mnacljduxclddus4xa83h079w0yqz94h22kxwxjqj26vu6fg2ckqc3gymn
    encrypted_regex: ^(data|stringData|password|token|secret)$
    lastmodified: "2026-05-24T20:31:44Z"
    mac: ENC[AES256_GCM,data:9Fz5JeOW3zZgYMUuI9M2slaHUU4LLN8E69WgkSZa2FdXNXZKzU1/oMxUV+GoCuy0ECdevjVNLKY7bwunW0NP7ElCZHwD+A8yO0wYoFUgart/vhARacYYeQVx22iWR2XWsNV5EUzama+Ws9qTXdJnzfdWU01EjkyRRS9JecbGGUo=,iv:z7fIB8LAQBrZnmF1iwgl5y0fG5tJq9twwImkRVLbTeQ=,tag:Ar50w2O53Cqn0CzdUbusVg==,type:str]
    version: 3.13.0
