apiVersion: garage.rajsingh.info/v1beta1
kind: GarageAdminToken
metadata:
  name: garage-admin
  namespace: garage-cluster
spec:
  clusterRef:
    name: garage-main-cluster
  secretTemplate:
    name: garage-admin-token
