apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 1h
  url: https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  interval: 15m0s
  chart:
    spec:
      chart: traefik
      version: "40.x.x"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
  values:
    deployment:
      kind: DaemonSet
    hostNetwork: false
    service:
      enabled: true
      type: LoadBalancer
      spec:
        externalTrafficPolicy: Local
    providers:
      kubernetesGateway:
        enabled: true
      kubernetesCRD:
        allowCrossNamespace: true
    gateway:
      enabled: false
    metrics:
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
        addRoutersLabels: true
        addServicesLabels: true
    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`server2`)
        entryPoints:
          - web
    ports:
      websecure:
        port: 443
        forwardedHeaders:
          trustedIPs:
            # K3s
            - 10.42.0.0/16
            - 10.43.0.0/16
            # Cloudflare
            - 173.245.48.0/20
            - 103.21.244.0/22
            - 103.22.200.0/22
            - 103.31.4.0/22
            - 141.101.64.0/18
            - 108.162.192.0/18
            - 190.93.240.0/20
            - 188.114.96.0/20
            - 197.234.240.0/22
            - 198.41.128.0/17
            - 162.158.0.0/15
            - 104.16.0.0/13
            - 104.24.0.0/14
            - 172.64.0.0/13
            - 131.0.72.0/22
            - 2400:cb00::/32
            - 2606:4700::/32
            - 2803:f800::/32
            - 2405:b500::/32
            - 2405:8100::/32
            - 2a06:98c0::/29
            - 2c0f:f248::/32
