apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: postgres
spec:
  instances: 2
  bootstrap:
    initdb:
      database: main_db
      owner: ephemeral
      secret:
        name: postgres-creds
  managed:
    roles:
      - name: ephemeral
        login: true
        passwordSecret:
          name: postgres-creds
  storage:
    size: 5Gi
    storageClass: longhorn
  monitoring:
    enablePodMonitor: true
