apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: postgres
spec:
  instances: 2
  postgresql:
    pg_hba:
      - host attic attic 0.0.0.0/0 scram-sha-256
      - host all attic 0.0.0.0/0 reject
      - host attic attic ::/0 scram-sha-256
      - host all attic ::/0 reject
      - host authentik authentik 0.0.0.0/0 scram-sha-256
      - host all authentik 0.0.0.0/0 reject
      - host authentik authentik ::/0 scram-sha-256
      - host all authentik ::/0 reject
      - host forgejo forgejo 0.0.0.0/0 scram-sha-256
      - host all forgejo 0.0.0.0/0 reject
      - host forgejo forgejo ::/0 scram-sha-256
      - host all forgejo ::/0 reject
  bootstrap:
    initdb:
      database: main_db
      owner: ephemeral
      secret:
        name: postgres-creds
  managed:
    roles:
      - name: ephemeral
        login: true
        superuser: false
        passwordSecret:
          name: postgres-creds
  storage:
    size: 5Gi
    storageClass: local-path
  monitoring:
    enablePodMonitor: true
