apiVersion: v1
kind: Secret
metadata:
    name: postgres-creds
    namespace: postgres
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:8ljGv9eDLOo3,iv:9AiRWd12GSnTzS7VI3A1i5MbqpiCbVaEyC33JMwrvb0=,tag:jMluB7cAe4B4eMMe6Qxlbg==,type:str]
    password: ENC[AES256_GCM,data:tyvKLPRGGE3RmAwMTacbWHbGM45rN1thki3DYexAPEyquvsX3uYQ7QzStLz5M4tDxM1x+FFvj61IXDPzPfknzQ==,iv:ezjzSDmFFGT1gtXbI+LOPANGEPJahaGcIdEDRMTxaPY=,tag:pdPJInyYfSP0rX9bmxn/nA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHEyMURhQSBOYWFr
            T2x2MFR1NnQrSHJLUnRESzRCdW9RUlpVS0xqNnBsazcvRmcwMnpBClBjcURSaGZ3
            VVUyclIwQXkxVmljUFhuUHRYK2VvNFMxenVmQzZnSzliWkEKLS0tIE00aXhIeDhm
            NjZaeDdJMWc4VWZMckd4a2FXY2hwV0I3aHZsNDRMckNvMGcKLefxw2HbKkXjfHls
            eioGnDSNB67/FdpUcaWN15btGRN1U//VGrhelz6+YoF3jqiJIEQW/H+kVLin+S9d
            7u3wRw==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICBbJZYAoaiso9r80YdbBkqFZ1bggET4EEkzZ9ckBbGW
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IHFodDFMQSBHV2JE
            N0tOL0JWSU1nOHVoZjRrMU9aZGpUZ3Q3aitvVFVraDNjK0FabW5VCjZZWFNhMzNH
            clJlRGlmTmJGcllId21kVzNDZi9rZGdEWU5hQ0NEZmxGa28KLS0tIEU2U294Vit1
            R0tHamRUQmVFWTNpNW1yNTRMUDUzdWowSSthNFZUdzZOUE0K2c+AP8hbyHaNjVu+
            J5ptCZb9LkQpqFQpQL6Qq65Tt0vwpPMO+Pc9UjK+TWz6+Hnt85gvg7m/UlyPx0Eb
            tn/sEw==
            -----END AGE ENCRYPTED FILE-----
          recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICvbJQ3KnO165S9pyfQ5qHXFv51cw3LmsvUn6Xo2Bbr7
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBNUsraFg3L2V6UHNrWVB6
            dmZGUDFBMm5uZG5SK0xMWGt3anJQZ0R6b2pvCjRVVGZKdVZnREszeUhDQWtobHNN
            aEpVb3ozZjNCaHVkanY3aHVBMmE2aWsKLS0tIGh0OVpYRHJoaFZBLzRKdHlJZ2NT
            NWs1cjFuNTA1eEVMK3lPQWsrbXcwZUUKCP0ADeOeJVoKlyXsd5fNbaEHv2+x5uHo
            Fle2nrcqfSi+uWTwnwtUABVgCVjP70WCvX9tolGurXQ+eJwvx3BzeA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1mnacljduxclddus4xa83h079w0yqz94h22kxwxjqj26vu6fg2ckqc3gymn
    encrypted_regex: ^(data|stringData|password|token|secret)$
    lastmodified: "2026-07-28T01:21:16Z"
    mac: ENC[AES256_GCM,data:lIwVGuqEav+nxmPDqP3aT6f9sOaKPiMqusyl38tsqX5l3vt6ifjDvVJv0eFBHUaRFQzwKVe33d9oJ1soWaeBKLROv9AropCL47CKIS72/sc3oszbMDN5MYYLSw32NdBghpI//qi+EZ1IpsEkFRJVG+nM4CP1/oAziXH+e1mduRo=,iv:zHk0a3YqTQQ7YlRYY1ugFDVWy1JbeR9tgDgv1/yfXR4=,tag:BmFur3SqInmjlaMVP0+HTA==,type:str]
    version: 3.13.0
