apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudflare-issuer.yaml
  - cloudflare-token.enc.yaml
  - CFmTLSenvoy.yaml
  - cloudflare-public.yaml
  - cfapi-dns-01-token.enc.yaml
