apiVersion: v1
kind: Secret
metadata:
  name: garage-rpc-secret
  namespace: garage-operator-system
type: Opaque
data:
  rpc-secret: ODg5ZWI3OGVhMTc2MDY5YjQ3ZWZiOWM2MjdmZGM5NjExZTQwY2QzMGRiODE3Y2Q3OWMyMGZlOTY2MjA5MzZmYQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: garage-admin-token
  namespace: garage-operator-system
type: Opaque
data:
  admin-token: MzgyOGZlN2QxZDhkZmY1YTdlOTcyZGI3Y2ZlZGNjODY=