---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: garage-operator
  namespace: flux-system
spec:
  interval: 15m0s
  url: oci://ghcr.io/rajsinghtech/charts/garage-operator
  ref:
    tag: "0.3.2"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: garage-operator
  namespace: garage-operator-system
spec:
  chart:
    spec:
      chart: garage-operator
      sourceRef:
        kind: OCIRepository
        name: garage-operator
        namespace: flux-system
  interval: 15m0s
  values:
    # Basic configuration