apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: garage-operator
  namespace: flux-system
spec:
  interval: 15m0s
  url: oci://ghcr.io/rajsinghtech
  type: oci
  passCredentials: false