apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: garage-operator-metrics
  namespace: garage-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: garage-operator-metrics
  endpoints:
    - port: metrics
      path: /metrics
      scheme: http
      interval: 30s
      #relabelings:
      #  - action: keep
      #    regex: metrics
      #    sourceLabels: [__meta_kubernetes_pod_container_port_name]
