apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: garage-operator-metrics
  namespace: garage-system
spec:
  # This selector should match the labels on the Service created by the garage-operator helm chart
  selector:
    matchLabels:
      app.kubernetes.io/name: garage-operator-metrics
  endpoints:
    - port: metrics # This should match the name of the port in the garage-operator Service
      path: /metrics
      interval: 30s
