apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: cloudflare-mtls
  namespace: ingress
spec:
  clientAuth:
    clientAuthType: RequireAndVerifyClientCert
    secretNames:
      - cloudflare-public
