apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway
  namespace: ingress
spec:
  gatewayClassName: envoy
  infrastructure:
    parametersRef:
      group: gateway.envoyproxy.io
      kind: EnvoyProxy
      name: envoy
  listeners:
    - name: websecure-tld
      port: 443
      protocol: HTTPS
      hostname: "maio-tech.com"
      tls:
        mode: Terminate
        certificateRefs:
          - name: tld-cert
        options:
          cert-manager.io/issuer: cf-origin-issuer
          cert-manager.io/issuer-kind: ClusterOriginIssuer
          cert-manager.io/issuer-group: cert-manager.k8s.cloudflare.com
      allowedRoutes:
        namespaces:
          from: All

    - name: websecure-sub
      port: 443
      protocol: HTTPS
      hostname: "*.maio-tech.com"
      tls:
        mode: Terminate
        certificateRefs:
          - name: sub-domain
        options:
          cert-manager.io/issuer: cf-origin-issuer
          cert-manager.io/issuer-kind: ClusterOriginIssuer
          cert-manager.io/issuer-group: cert-manager.k8s.cloudflare.com
      allowedRoutes:
        namespaces:
          from: All

    - name: websecure-attic
      port: 443
      protocol: HTTPS
      hostname: "attic.maio-tech.com"
      tls:
        mode: Terminate
        certificateRefs:
          - name: attic-letsencrypt-cert
        options:
          cert-manager.io/issuer: lets-encrypt-issuer
          cert-manager.io/issuer-kind: Issuer
      allowedRoutes:
        namespaces:
          from: All
