apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: lets-encrypt-issuer
  namespace: ingress
spec:
  acme:
    email: sammyrules100@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: lets-encrypt-issuer-account-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-dns-01-token
              key: api-token
